<?php

namespace App\Http\Controllers\V1;

use Siakad\Controller;

class KeluargaMhsController extends Controller
{
    /**
     *
     * @OA\Get(
     *      path="/v1/keluarga-mhs",
     *      tags={"Keluarga mhs"},
     *      summary="List Keluarga mhs",
     *      security={{"bearerAuth": {}}},
     *      @OA\Response(
     *          response=200,
     *          description="Get list of keluarga mhs.",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(property="data", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="id", type="integer", example=""),
     *                      @OA\Property(property="id_mahasiswa", type="integer", example=""),
     *                      @OA\Property(property="status_keluarga", type="string", example=""),
     *                      @OA\Property(property="nama", type="string", example=""),
     *                      @OA\Property(property="tgl_lahir", type="date", example=""),
     *                      @OA\Property(property="alamat", type="string", example=""),
     *                      @OA\Property(property="telepon", type="string", example=""),
     *                      @OA\Property(property="email", type="string", example=""),
     *                      @OA\Property(property="nik", type="string", example=""),
     *                      @OA\Property(property="is_nik_aktif", type="string", example=""),
     *                      @OA\Property(property="id_jenjang", type="integer", example=""),
     *                      @OA\Property(property="id_pekerjaan", type="integer", example=""),
     *                      @OA\Property(property="id_penghasilan", type="integer", example=""),
     *                      @OA\Property(property="instansi_kerja", type="string", example=""),
     *                      @OA\Property(property="status_kondisi", type="string", example=""),
     *                      @OA\Property(property="status_kerabat", type="string", example=""),
     *                  ),
     *              ),
     *              @OA\Property(property="info", type="object",
     *                      @OA\Property(property="total", type="integer", example=10),
     *                      @OA\Property(property="page", type="integer", example=1),
     *                      @OA\Property(property="last_page", type="integer", example=1),
     *                      @OA\Property(property="count", type="integer", example=10),
     *                      @OA\Property(property="start", type="integer", example=1),
     *                      @OA\Property(property="end", type="integer", example=10),
     *              ),
     *              @OA\Property(property="debug", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="query", type="string", example="select count(*) as aggregate from ak_keluarga_mhs"),
     *                      @OA\Property(property="time", type="integer", example=59.0),
     *                  ),
     *              ),
     *          ),
     *       ),
     * )
     */

    /**
     * @OA\Get(
     *     path="/v1/keluarga-mhs/{id}",
     *     summary="Data Keluarga mhs",
     *     tags={"Keluarga mhs"},
     *     security={{"bearerAuth": {}}},
     *     @OA\Parameter(
     *         description="id keluarga mhs",
     *         in="path",
     *         name="id",
     *         required=true,
     *         @OA\Schema(type="integer"),
     *         @OA\Examples(example="int", value="1", summary="An int value."),
     *     ),
     *     @OA\Response(
     *          response=200,
     *          description="Get data of keluarga mhs.",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(property="data", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="id", type="integer", example=""),
     *                      @OA\Property(property="id_mahasiswa", type="integer", example=""),
     *                      @OA\Property(property="status_keluarga", type="string", example=""),
     *                      @OA\Property(property="nama", type="string", example=""),
     *                      @OA\Property(property="tgl_lahir", type="date", example=""),
     *                      @OA\Property(property="alamat", type="string", example=""),
     *                      @OA\Property(property="telepon", type="string", example=""),
     *                      @OA\Property(property="email", type="string", example=""),
     *                      @OA\Property(property="nik", type="string", example=""),
     *                      @OA\Property(property="is_nik_aktif", type="string", example=""),
     *                      @OA\Property(property="id_jenjang", type="integer", example=""),
     *                      @OA\Property(property="id_pekerjaan", type="integer", example=""),
     *                      @OA\Property(property="id_penghasilan", type="integer", example=""),
     *                      @OA\Property(property="instansi_kerja", type="string", example=""),
     *                      @OA\Property(property="status_kondisi", type="string", example=""),
     *                      @OA\Property(property="status_kerabat", type="string", example=""),
     *                  ),
     *              ),
     *              @OA\Property(property="debug", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="query", type="string", example="SELECT * FROM ak_keluarga_mhs WHERE ak_keluarga_mhs.id = 1 limit 1"),
     *                      @OA\Property(property="time", type="integer", example=59.0),
     *                  ),
     *              ),
     *          ),
     *     ),
     *     @OA\Response(response=404, description="Error: Not Found",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(property="error", type="object",
     *                      @OA\Property(property="code", type="integer", example=404),
     *                      @OA\Property(property="message", type="string", example="Data tidak ditemukan"),
     *                      @OA\Property(property="debug", type="object",
     *                          @OA\Property(property="message", type="string", example="No query results for model [App\Models\KeluargaMhs] 1"),
     *                          @OA\Property(property="files", type="object",
     *                              @OA\Property(type="string", example="/Users/brondol/Applications/siakadcloud/master/vendor/illuminate/database/Eloquent/Builder.php baris 434"),
     *                          ),
     *                      ),
     *              ),
     *              @OA\Property(property="debug", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="query", type="string", example="select * from ak_mahasiswa where ak_mahasiswa.id = 1 limit 1"),
     *                      @OA\Property(property="time", type="integer", example=2.25),
     *                  ),
     *              ),
     *          ),
     *     ),
     * )
     */

    /**
     * @OA\Post(
     *     path="/v1/keluarga-mhs",
     *     summary="Add Keluarga mhs",
     *     tags={"Keluarga mhs"},
     *     security={{"bearerAuth": {}}},
     *     @OA\RequestBody(
     *         @OA\MediaType(
     *             mediaType="application/json",
     *             @OA\Schema(
     *                 @OA\Property(property="id_mahasiswa", type="integer", example=""),
     *                 @OA\Property(property="status_keluarga", type="string", example=""),
     *                 @OA\Property(property="nama", type="string", example=""),
     *                 @OA\Property(property="tgl_lahir", type="date", example=""),
     *                 @OA\Property(property="alamat", type="string", example=""),
     *                 @OA\Property(property="telepon", type="string", example=""),
     *                 @OA\Property(property="email", type="string", example=""),
     *                 @OA\Property(property="nik", type="string", example=""),
     *                 @OA\Property(property="is_nik_aktif", type="string", example=""),
     *                 @OA\Property(property="id_jenjang", type="integer", example=""),
     *                 @OA\Property(property="id_pekerjaan", type="integer", example=""),
     *                 @OA\Property(property="id_penghasilan", type="integer", example=""),
     *                 @OA\Property(property="instansi_kerja", type="string", example=""),
     *                 @OA\Property(property="status_kondisi", type="string", example=""),
     *                 @OA\Property(property="status_kerabat", type="string", example=""),
     *             )
     *         )
     *     ),
     *     @OA\Response(
     *          response=201,
     *          description="Success add new keluarga mhs.",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(property="data", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="id", type="integer", example=""),
     *                      @OA\Property(property="id_mahasiswa", type="integer", example=""),
     *                      @OA\Property(property="status_keluarga", type="string", example=""),
     *                      @OA\Property(property="nama", type="string", example=""),
     *                      @OA\Property(property="tgl_lahir", type="date", example=""),
     *                      @OA\Property(property="alamat", type="string", example=""),
     *                      @OA\Property(property="telepon", type="string", example=""),
     *                      @OA\Property(property="email", type="string", example=""),
     *                      @OA\Property(property="nik", type="string", example=""),
     *                      @OA\Property(property="is_nik_aktif", type="string", example=""),
     *                      @OA\Property(property="id_jenjang", type="integer", example=""),
     *                      @OA\Property(property="id_pekerjaan", type="integer", example=""),
     *                      @OA\Property(property="id_penghasilan", type="integer", example=""),
     *                      @OA\Property(property="instansi_kerja", type="string", example=""),
     *                      @OA\Property(property="status_kondisi", type="string", example=""),
     *                      @OA\Property(property="status_kerabat", type="string", example=""),
     *                  ),
     *              ),
     *              @OA\Property(property="debug", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="query", type="string", example="insert into ak_keluarga_mhs () values () returning id"),
     *                      @OA\Property(property="time", type="integer", example=8.13),
     *                  ),
     *              ),
     *          ),
     *     ),
     *     @OA\Response(response=400, description="Bad Request",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(property="error", type="object",
     *                      @OA\Property(property="code", type="integer", example=400),
     *                      @OA\Property(property="message", type="string", example="Data yang dikirimkan tidak valid"),
     *                      @OA\Property(property="validation", type="object",
     *                          @OA\Property(property="nama_field", type="array",
     *                              @OA\Items(type="string", example="Harus diisi"),
     *                          ),
     *                      ),
     *              ),
     *          ),
     *     ),
     * )
     */

    /**
     * @OA\Put(
     *     path="/v1/keluarga-mhs/{id}",
     *     summary="Update keluarga mhs",
     *     tags={"Keluarga mhs"},
     *     security={{"bearerAuth": {}}},
     *     @OA\Parameter(
     *         description="id keluarga mhs",
     *         in="path",
     *         name="id",
     *         required=true,
     *         @OA\Schema(type="integer"),
     *         @OA\Examples(example="int", value="1", summary="An int value."),
     *     ),
     *     @OA\RequestBody(
     *         @OA\MediaType(
     *             mediaType="application/json",
     *             @OA\Schema(
     *                 @OA\Property(property="id_mahasiswa", type="integer", example=""),
     *                 @OA\Property(property="status_keluarga", type="string", example=""),
     *                 @OA\Property(property="nama", type="string", example=""),
     *                 @OA\Property(property="tgl_lahir", type="date", example=""),
     *                 @OA\Property(property="alamat", type="string", example=""),
     *                 @OA\Property(property="telepon", type="string", example=""),
     *                 @OA\Property(property="email", type="string", example=""),
     *                 @OA\Property(property="nik", type="string", example=""),
     *                 @OA\Property(property="is_nik_aktif", type="string", example=""),
     *                 @OA\Property(property="id_jenjang", type="integer", example=""),
     *                 @OA\Property(property="id_pekerjaan", type="integer", example=""),
     *                 @OA\Property(property="id_penghasilan", type="integer", example=""),
     *                 @OA\Property(property="instansi_kerja", type="string", example=""),
     *                 @OA\Property(property="status_kondisi", type="string", example=""),
     *                 @OA\Property(property="status_kerabat", type="string", example=""),
     *             )
     *         )
     *     ),
     *     @OA\Response(
     *          response=200,
     *          description="Success Update Keluarga mhs.",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(property="data", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="id", type="integer", example=""),
     *                      @OA\Property(property="id_mahasiswa", type="integer", example=""),
     *                      @OA\Property(property="status_keluarga", type="string", example=""),
     *                      @OA\Property(property="nama", type="string", example=""),
     *                      @OA\Property(property="tgl_lahir", type="date", example=""),
     *                      @OA\Property(property="alamat", type="string", example=""),
     *                      @OA\Property(property="telepon", type="string", example=""),
     *                      @OA\Property(property="email", type="string", example=""),
     *                      @OA\Property(property="nik", type="string", example=""),
     *                      @OA\Property(property="is_nik_aktif", type="string", example=""),
     *                      @OA\Property(property="id_jenjang", type="integer", example=""),
     *                      @OA\Property(property="id_pekerjaan", type="integer", example=""),
     *                      @OA\Property(property="id_penghasilan", type="integer", example=""),
     *                      @OA\Property(property="instansi_kerja", type="string", example=""),
     *                      @OA\Property(property="status_kondisi", type="string", example=""),
     *                      @OA\Property(property="status_kerabat", type="string", example=""),
     *                  ),
     *              ),
     *              @OA\Property(property="debug", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="query", type="string", example="update ak_keluarga_mhs set ak_keluarga_mhs.id = 1 where ak_keluarga_mhs.id = 1"),
     *                      @OA\Property(property="time", type="integer", example=8.13),
     *                  ),
     *              ),
     *          ),
     *       ),
     *     @OA\Response(response=404, description="Error: Not Found",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(property="error", type="object",
     *                      @OA\Property(property="code", type="integer", example=404),
     *                      @OA\Property(property="message", type="string", example="Data tidak ditemukan"),
     *                      @OA\Property(property="debug", type="object",
     *                          @OA\Property(property="message", type="string", example="No query results for model [App\Models\KeluargaMhs] 1"),
     *                          @OA\Property(property="files", type="object",
     *                              @OA\Property(type="string", example="/Users/brondol/Applications/siakadcloud/master/vendor/illuminate/database/Eloquent/Builder.php baris 434"),
     *                          ),
     *                      ),
     *              ),
     *              @OA\Property(property="debug", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="query", type="string", example="select * from ak_mahasiswa where ak_mahasiswa.id = 1 limit 1"),
     *                      @OA\Property(property="time", type="integer", example=2.25),
     *                  ),
     *              ),
     *          ),
     *     ),
     * )
     */

    /**
     * @OA\Delete(
     *     path="/v1/keluarga-mhs/{id}",
     *     summary="Delete keluarga mhs",
     *     tags={"Keluarga mhs"},
     *     security={{"bearerAuth": {}}},
     *     @OA\Parameter(
     *         description="id keluarga mhs",
     *         in="path",
     *         name="id",
     *         required=true,
     *         @OA\Schema(type="integer"),
     *         @OA\Examples(example="int", value="1", summary="An int value."),
     *     ),
     *     @OA\Response(
     *          response=200,
     *          description="Berhasil Menghapus Keluarga mhs"
     *       ),
     *     @OA\Response(response=404, description="Error: Not Found",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(property="error", type="object",
     *                      @OA\Property(property="code", type="integer", example=404),
     *                      @OA\Property(property="message", type="string", example="Data tidak ditemukan"),
     *                      @OA\Property(property="debug", type="object",
     *                          @OA\Property(property="message", type="string", example="No query results for model [App\Models\KeluargaMhs] 1"),
     *                          @OA\Property(property="files", type="object",
     *                              @OA\Property(type="string", example="/Users/brondol/Applications/siakadcloud/master/vendor/illuminate/database/Eloquent/Builder.php baris 434"),
     *                          ),
     *                      ),
     *              ),
     *              @OA\Property(property="debug", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="query", type="string", example="select * from ak_mahasiswa where ak_mahasiswa.id = 1 limit 1"),
     *                      @OA\Property(property="time", type="integer", example=2.25),
     *                  ),
     *              ),
     *          ),
     *     ),
     * )
     */

    /**
     *     @OA\Schema(
     *         schema="Keluarga mhs",
     *         @OA\Xml(name="Keluarga mhs"),
     *         @OA\Property(property="id", type="integer", example=""),
     *         @OA\Property(property="id_mahasiswa", type="integer", example=""),
     *         @OA\Property(property="status_keluarga", type="string", example=""),
     *         @OA\Property(property="nama", type="string", example=""),
     *         @OA\Property(property="tgl_lahir", type="date", example=""),
     *         @OA\Property(property="alamat", type="string", example=""),
     *         @OA\Property(property="telepon", type="string", example=""),
     *         @OA\Property(property="email", type="string", example=""),
     *         @OA\Property(property="nik", type="string", example=""),
     *         @OA\Property(property="is_nik_aktif", type="string", example=""),
     *         @OA\Property(property="id_jenjang", type="integer", example=""),
     *         @OA\Property(property="id_pekerjaan", type="integer", example=""),
     *         @OA\Property(property="id_penghasilan", type="integer", example=""),
     *         @OA\Property(property="instansi_kerja", type="string", example=""),
     *         @OA\Property(property="status_kondisi", type="string", example=""),
     *         @OA\Property(property="status_kerabat", type="string", example=""),
     *     ),
     */
}
        