<?php

namespace App\Http\Controllers\V1;

use Siakad\Controller;

class KotaController extends Controller
{
    /**
     *
     * @OA\Get(
     *      path="/v1/kota",
     *      tags={"Kota"},
     *      summary="List Kota",
     *      security={{"bearerAuth": {}}},
     *      @OA\Response(
     *          response=200,
     *          description="Get list of kota.",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(property="data", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="id", type="integer", example=1),
     *                      @OA\Property(property="kode_kota", type="string", example="1"),
     *                      @OA\Property(property="nama_kota", type="string", example="Bandar Lampung"),
     *                      @OA\Property(property="id_parent", type="integer", example=1),
     *                      @OA\Property(property="level", type="string", example=1),
     *                      @OA\Property(property="kode_iso", type="string", example="3166"),
     *                      @OA\Property(property="kode_dikti", type="string", example="001026"),
     *                  ),
     *              ),
     *              @OA\Property(property="info", type="object",
     *                      @OA\Property(property="total", type="integer", example=10),
     *                      @OA\Property(property="page", type="integer", example=1),
     *                      @OA\Property(property="last_page", type="integer", example=1),
     *                      @OA\Property(property="count", type="integer", example=10),
     *                      @OA\Property(property="start", type="integer", example=1),
     *                      @OA\Property(property="end", type="integer", example=10),
     *              ),
     *              @OA\Property(property="debug", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="query", type="string", example="select count(*) as aggregate from lv_kota"),
     *                      @OA\Property(property="time", type="integer", example=59.0),
     *                  ),
     *              ),
     *          ),
     *       ),
     * )
     */

    /**
     * @OA\Get(
     *     path="/v1/kota/{id}",
     *     summary="Data Kota",
     *     tags={"Kota"},
     *     security={{"bearerAuth": {}}},
     *     @OA\Parameter(
     *         description="id kota",
     *         in="path",
     *         name="id",
     *         required=true,
     *         @OA\Schema(type="integer"),
     *         @OA\Examples(example="int", value="1", summary="An int value."),
     *     ),
     *     @OA\Response(
     *          response=200,
     *          description="Get data of kota.",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(property="data", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="id", type="integer", example=1),
     *                      @OA\Property(property="kode_kota", type="string", example="1"),
     *                      @OA\Property(property="nama_kota", type="string", example="Bandar Lampung"),
     *                      @OA\Property(property="id_parent", type="integer", example=1),
     *                      @OA\Property(property="level", type="string", example=1),
     *                      @OA\Property(property="kode_iso", type="string", example="3166"),
     *                      @OA\Property(property="kode_dikti", type="string", example="001026"),
     *                  ),
     *              ),
     *              @OA\Property(property="debug", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="query", type="string", example="SELECT * FROM lv_kota WHERE lv_kota.id = 1 limit 1"),
     *                      @OA\Property(property="time", type="integer", example=59.0),
     *                  ),
     *              ),
     *          ),
     *     ),
     *     @OA\Response(response=404, description="Error: Not Found",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(property="error", type="object",
     *                      @OA\Property(property="code", type="integer", example=404),
     *                      @OA\Property(property="message", type="string", example="Data tidak ditemukan"),
     *                      @OA\Property(property="debug", type="object",
     *                          @OA\Property(property="message", type="string", example="No query results for model [App\Models\Kota] 1"),
     *                          @OA\Property(property="files", type="object",
     *                              @OA\Property(type="string", example="/Users/brondol/Applications/siakadcloud/master/vendor/illuminate/database/Eloquent/Builder.php baris 434"),
     *                          ),
     *                      ),
     *              ),
     *              @OA\Property(property="debug", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="query", type="string", example="select * from ak_mahasiswa where ak_mahasiswa.id = 1 limit 1"),
     *                      @OA\Property(property="time", type="integer", example=2.25),
     *                  ),
     *              ),
     *          ),
     *     ),
     * )
     */

    /**
     * @OA\Post(
     *     path="/v1/kota",
     *     summary="Add Kota",
     *     tags={"Kota"},
     *     security={{"bearerAuth": {}}},
     *     @OA\RequestBody(
     *         @OA\MediaType(
     *             mediaType="application/json",
     *             @OA\Schema(
     *                 @OA\Property(property="kode_kota", type="string", example="1"),
     *                 @OA\Property(property="nama_kota", type="string", example="Bandar Lampung"),
     *                 @OA\Property(property="id_parent", type="integer", example=1),
     *                 @OA\Property(property="level", type="string", example=1),
     *                 @OA\Property(property="kode_iso", type="string", example="3166"),
     *                 @OA\Property(property="kode_dikti", type="string", example="001026"),
     *             )
     *         )
     *     ),
     *     @OA\Response(
     *          response=201,
     *          description="Success add new kota.",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(property="data", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="id", type="integer", example=1),
     *                      @OA\Property(property="kode_kota", type="string", example="1"),
     *                      @OA\Property(property="nama_kota", type="string", example="Bandar Lampung"),
     *                      @OA\Property(property="id_parent", type="integer", example=1),
     *                      @OA\Property(property="level", type="string", example=1),
     *                      @OA\Property(property="kode_iso", type="string", example="3166"),
     *                      @OA\Property(property="kode_dikti", type="string", example="001026"),
     *                  ),
     *              ),
     *              @OA\Property(property="debug", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="query", type="string", example="insert into lv_kota () values () returning id"),
     *                      @OA\Property(property="time", type="integer", example=8.13),
     *                  ),
     *              ),
     *          ),
     *     ),
     *     @OA\Response(response=400, description="Bad Request",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(property="error", type="object",
     *                      @OA\Property(property="code", type="integer", example=400),
     *                      @OA\Property(property="message", type="string", example="Data yang dikirimkan tidak valid"),
     *                      @OA\Property(property="validation", type="object",
     *                          @OA\Property(property="nama_field", type="array",
     *                              @OA\Items(type="string", example="Harus diisi"),
     *                          ),
     *                      ),
     *              ),
     *          ),
     *     ),
     * )
     */

    /**
     * @OA\Put(
     *     path="/v1/kota/{id}",
     *     summary="Update kota",
     *     tags={"Kota"},
     *     security={{"bearerAuth": {}}},
     *     @OA\Parameter(
     *         description="id kota",
     *         in="path",
     *         name="id",
     *         required=true,
     *         @OA\Schema(type="integer"),
     *         @OA\Examples(example="int", value="1", summary="An int value."),
     *     ),
     *     @OA\RequestBody(
     *         @OA\MediaType(
     *             mediaType="application/json",
     *             @OA\Schema(
     *                 @OA\Property(property="kode_kota", type="string", example="1"),
     *                 @OA\Property(property="nama_kota", type="string", example="Bandar Lampung"),
     *                 @OA\Property(property="id_parent", type="integer", example=1),
     *                 @OA\Property(property="level", type="string", example=1),
     *                 @OA\Property(property="kode_iso", type="string", example="3166"),
     *                 @OA\Property(property="kode_dikti", type="string", example="001026"),
     *             )
     *         )
     *     ),
     *     @OA\Response(
     *          response=200,
     *          description="Success Update Kota.",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(property="data", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="id", type="integer", example=1),
     *                      @OA\Property(property="kode_kota", type="string", example="1"),
     *                      @OA\Property(property="nama_kota", type="string", example="Bandar Lampung"),
     *                      @OA\Property(property="id_parent", type="integer", example=1),
     *                      @OA\Property(property="level", type="string", example=1),
     *                      @OA\Property(property="kode_iso", type="string", example="3166"),
     *                      @OA\Property(property="kode_dikti", type="string", example="001026"),
     *                  ),
     *              ),
     *              @OA\Property(property="debug", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="query", type="string", example="update lv_kota set lv_kota.id = 1 where lv_kota.id = 1"),
     *                      @OA\Property(property="time", type="integer", example=8.13),
     *                  ),
     *              ),
     *          ),
     *       ),
     *     @OA\Response(response=404, description="Error: Not Found",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(property="error", type="object",
     *                      @OA\Property(property="code", type="integer", example=404),
     *                      @OA\Property(property="message", type="string", example="Data tidak ditemukan"),
     *                      @OA\Property(property="debug", type="object",
     *                          @OA\Property(property="message", type="string", example="No query results for model [App\Models\Kota] 1"),
     *                          @OA\Property(property="files", type="object",
     *                              @OA\Property(type="string", example="/Users/brondol/Applications/siakadcloud/master/vendor/illuminate/database/Eloquent/Builder.php baris 434"),
     *                          ),
     *                      ),
     *              ),
     *              @OA\Property(property="debug", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="query", type="string", example="select * from ak_mahasiswa where ak_mahasiswa.id = 1 limit 1"),
     *                      @OA\Property(property="time", type="integer", example=2.25),
     *                  ),
     *              ),
     *          ),
     *     ),
     * )
     */

    /**
     * @OA\Delete(
     *     path="/v1/kota/{id}",
     *     summary="Delete kota",
     *     tags={"Kota"},
     *     security={{"bearerAuth": {}}},
     *     @OA\Parameter(
     *         description="id kota",
     *         in="path",
     *         name="id",
     *         required=true,
     *         @OA\Schema(type="integer"),
     *         @OA\Examples(example="int", value="1", summary="An int value."),
     *     ),
     *     @OA\Response(
     *          response=200,
     *          description="Berhasil Menghapus Kota"
     *       ),
     *     @OA\Response(response=404, description="Error: Not Found",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(property="error", type="object",
     *                      @OA\Property(property="code", type="integer", example=404),
     *                      @OA\Property(property="message", type="string", example="Data tidak ditemukan"),
     *                      @OA\Property(property="debug", type="object",
     *                          @OA\Property(property="message", type="string", example="No query results for model [App\Models\Kota] 1"),
     *                          @OA\Property(property="files", type="object",
     *                              @OA\Property(type="string", example="/Users/brondol/Applications/siakadcloud/master/vendor/illuminate/database/Eloquent/Builder.php baris 434"),
     *                          ),
     *                      ),
     *              ),
     *              @OA\Property(property="debug", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="query", type="string", example="select * from ak_mahasiswa where ak_mahasiswa.id = 1 limit 1"),
     *                      @OA\Property(property="time", type="integer", example=2.25),
     *                  ),
     *              ),
     *          ),
     *     ),
     * )
     */

    /**
     *     @OA\Schema(
     *         schema="Kota",
     *         @OA\Xml(name="Kota"),
     *         @OA\Property(property="id", type="integer", example=1),
     *         @OA\Property(property="kode_kota", type="string", example="1"),
     *         @OA\Property(property="nama_kota", type="string", example="Bandar Lampung"),
     *         @OA\Property(property="id_parent", type="integer", example=1),
     *         @OA\Property(property="level", type="string", example=1),
     *         @OA\Property(property="kode_iso", type="string", example="3166"),
     *         @OA\Property(property="kode_dikti", type="string", example="001026"),
     *     ),
     */
}
