<?php

namespace App\Http\Controllers\V1;

use Siakad\Controller;

class MahasiswaPtController extends Controller
{
    /**
     *
     * @OA\Get(
     *      path="/v1/mahasiswa-pt",
     *      tags={"Mahasiswa pt"},
     *      summary="List Mahasiswa pt",
     *      security={{"bearerAuth": {}}},
     *      @OA\Response(
     *          response=200,
     *          description="Get list of mahasiswa pt.",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(property="data", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="id", type="integer", example=""),
     *                      @OA\Property(property="id_mahasiswa", type="integer", example=""),
     *                      @OA\Property(property="nim", type="string", example=""),
     *                      @OA\Property(property="id_periode", type="integer", example=""),
     *                      @OA\Property(property="id_unit", type="integer", example=""),
     *                      @OA\Property(property="id_tahun", type="integer", example=""),
     *                      @OA\Property(property="id_jalur", type="integer", example=""),
     *                      @OA\Property(property="id_gelombang", type="integer", example=""),
     *                      @OA\Property(property="id_sistem", type="integer", example=""),
     *                      @OA\Property(property="id_kelas", type="integer", example=""),
     *                      @OA\Property(property="id_bidang", type="integer", example=""),
     *                      @OA\Property(property="id_periode_akhir", type="integer", example=""),
     *                      @OA\Property(property="email_kampus", type="string", example=""),
     *                      @OA\Property(property="tgl_daftar", type="date", example=""),
     *                      @OA\Property(property="nilai_tpa", type="decimal", example=""),
     *                      @OA\Property(property="nilai_kesehatan", type="decimal", example=""),
     *                      @OA\Property(property="nilai_psikotes", type="decimal", example=""),
     *                      @OA\Property(property="nilai_wawancara", type="decimal", example=""),
     *                      @OA\Property(property="jenis_transfer", type="string", example=""),
     *                      @OA\Property(property="kode_transfer", type="string", example=""),
     *                      @OA\Property(property="kode_pendidikan_asal", type="string", example=""),
     *                      @OA\Property(property="asal_smu", type="string", example=""),
     *                      @OA\Property(property="alamat_smu", type="string", example=""),
     *                      @OA\Property(property="telepon_smu", type="string", example=""),
     *                      @OA\Property(property="jurusan_smu", type="string", example=""),
     *                      @OA\Property(property="thn_lulus_smu", type="integer", example=""),
     *                      @OA\Property(property="nem_smu", type="decimal", example=""),
     *                      @OA\Property(property="no_ijasah_smu", type="string", example=""),
     *                      @OA\Property(property="nisn", type="string", example=""),
     *                      @OA\Property(property="nupn", type="string", example=""),
     *                      @OA\Property(property="id_kota_smu", type="integer", example=""),
     *                      @OA\Property(property="id_propinsi_smu", type="integer", example=""),
     *                      @OA\Property(property="tgl_transfer", type="date", example=""),
     *                      @OA\Property(property="nim_lama", type="string", example=""),
     *                      @OA\Property(property="asal_pt", type="string", example=""),
     *                      @OA\Property(property="prodi_pt", type="string", example=""),
     *                      @OA\Property(property="nim_pt", type="string", example=""),
     *                      @OA\Property(property="ipk_asal", type="decimal", example=""),
     *                      @OA\Property(property="sks_asal", type="integer", example=""),
     *                      @OA\Property(property="npsn", type="string", example=""),
     *                      @OA\Property(property="id_periode_transfer", type="integer", example=""),
     *                      @OA\Property(property="id_unit_asal", type="integer", example=""),
     *                      @OA\Property(property="id_tahun_asal", type="integer", example=""),
     *                      @OA\Property(property="id_universitas", type="integer", example=""),
     *                      @OA\Property(property="id_universitas_prodi", type="integer", example=""),
     *                      @OA\Property(property="nirm", type="string", example=""),
     *                      @OA\Property(property="nirl", type="string", example=""),
     *                      @OA\Property(property="id_almamater", type="integer", example=""),
     *                      @OA\Property(property="is_valid_email", type="string", example=""),
     *                      @OA\Property(property="id_file_transkrip_asal", type="guid", example=""),
     *                      @OA\Property(property="id_file_ijazah_akhir", type="guid", example=""),
     *                      @OA\Property(property="id_file_surat_pindah", type="guid", example=""),
     *                  ),
     *              ),
     *              @OA\Property(property="info", type="object",
     *                      @OA\Property(property="total", type="integer", example=10),
     *                      @OA\Property(property="page", type="integer", example=1),
     *                      @OA\Property(property="last_page", type="integer", example=1),
     *                      @OA\Property(property="count", type="integer", example=10),
     *                      @OA\Property(property="start", type="integer", example=1),
     *                      @OA\Property(property="end", type="integer", example=10),
     *              ),
     *              @OA\Property(property="debug", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="query", type="string", example="select count(*) as aggregate from ak_mahasiswa_pt"),
     *                      @OA\Property(property="time", type="integer", example=59.0),
     *                  ),
     *              ),
     *          ),
     *       ),
     * )
     */

    /**
     * @OA\Get(
     *     path="/v1/mahasiswa-pt/{id}",
     *     summary="Data Mahasiswa pt",
     *     tags={"Mahasiswa pt"},
     *     security={{"bearerAuth": {}}},
     *     @OA\Parameter(
     *         description="id mahasiswa pt",
     *         in="path",
     *         name="id",
     *         required=true,
     *         @OA\Schema(type="integer"),
     *         @OA\Examples(example="int", value="1", summary="An int value."),
     *     ),
     *     @OA\Response(
     *          response=200,
     *          description="Get data of mahasiswa pt.",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(property="data", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="id", type="integer", example=""),
     *                      @OA\Property(property="id_mahasiswa", type="integer", example=""),
     *                      @OA\Property(property="nim", type="string", example=""),
     *                      @OA\Property(property="id_periode", type="integer", example=""),
     *                      @OA\Property(property="id_unit", type="integer", example=""),
     *                      @OA\Property(property="id_tahun", type="integer", example=""),
     *                      @OA\Property(property="id_jalur", type="integer", example=""),
     *                      @OA\Property(property="id_gelombang", type="integer", example=""),
     *                      @OA\Property(property="id_sistem", type="integer", example=""),
     *                      @OA\Property(property="id_kelas", type="integer", example=""),
     *                      @OA\Property(property="id_bidang", type="integer", example=""),
     *                      @OA\Property(property="id_periode_akhir", type="integer", example=""),
     *                      @OA\Property(property="email_kampus", type="string", example=""),
     *                      @OA\Property(property="tgl_daftar", type="date", example=""),
     *                      @OA\Property(property="nilai_tpa", type="decimal", example=""),
     *                      @OA\Property(property="nilai_kesehatan", type="decimal", example=""),
     *                      @OA\Property(property="nilai_psikotes", type="decimal", example=""),
     *                      @OA\Property(property="nilai_wawancara", type="decimal", example=""),
     *                      @OA\Property(property="jenis_transfer", type="string", example=""),
     *                      @OA\Property(property="kode_transfer", type="string", example=""),
     *                      @OA\Property(property="kode_pendidikan_asal", type="string", example=""),
     *                      @OA\Property(property="asal_smu", type="string", example=""),
     *                      @OA\Property(property="alamat_smu", type="string", example=""),
     *                      @OA\Property(property="telepon_smu", type="string", example=""),
     *                      @OA\Property(property="jurusan_smu", type="string", example=""),
     *                      @OA\Property(property="thn_lulus_smu", type="integer", example=""),
     *                      @OA\Property(property="nem_smu", type="decimal", example=""),
     *                      @OA\Property(property="no_ijasah_smu", type="string", example=""),
     *                      @OA\Property(property="nisn", type="string", example=""),
     *                      @OA\Property(property="nupn", type="string", example=""),
     *                      @OA\Property(property="id_kota_smu", type="integer", example=""),
     *                      @OA\Property(property="id_propinsi_smu", type="integer", example=""),
     *                      @OA\Property(property="tgl_transfer", type="date", example=""),
     *                      @OA\Property(property="nim_lama", type="string", example=""),
     *                      @OA\Property(property="asal_pt", type="string", example=""),
     *                      @OA\Property(property="prodi_pt", type="string", example=""),
     *                      @OA\Property(property="nim_pt", type="string", example=""),
     *                      @OA\Property(property="ipk_asal", type="decimal", example=""),
     *                      @OA\Property(property="sks_asal", type="integer", example=""),
     *                      @OA\Property(property="npsn", type="string", example=""),
     *                      @OA\Property(property="id_periode_transfer", type="integer", example=""),
     *                      @OA\Property(property="id_unit_asal", type="integer", example=""),
     *                      @OA\Property(property="id_tahun_asal", type="integer", example=""),
     *                      @OA\Property(property="id_universitas", type="integer", example=""),
     *                      @OA\Property(property="id_universitas_prodi", type="integer", example=""),
     *                      @OA\Property(property="nirm", type="string", example=""),
     *                      @OA\Property(property="nirl", type="string", example=""),
     *                      @OA\Property(property="id_almamater", type="integer", example=""),
     *                      @OA\Property(property="is_valid_email", type="string", example=""),
     *                      @OA\Property(property="id_file_transkrip_asal", type="guid", example=""),
     *                      @OA\Property(property="id_file_ijazah_akhir", type="guid", example=""),
     *                      @OA\Property(property="id_file_surat_pindah", type="guid", example=""),
     *                  ),
     *              ),
     *              @OA\Property(property="debug", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="query", type="string", example="SELECT * FROM ak_mahasiswa_pt WHERE ak_mahasiswa_pt.id = 1 limit 1"),
     *                      @OA\Property(property="time", type="integer", example=59.0),
     *                  ),
     *              ),
     *          ),
     *     ),
     *     @OA\Response(response=404, description="Error: Not Found",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(property="error", type="object",
     *                      @OA\Property(property="code", type="integer", example=404),
     *                      @OA\Property(property="message", type="string", example="Data tidak ditemukan"),
     *                      @OA\Property(property="debug", type="object",
     *                          @OA\Property(property="message", type="string", example="No query results for model [App\Models\MahasiswaPt] 1"),
     *                          @OA\Property(property="files", type="object",
     *                              @OA\Property(type="string", example="/Users/brondol/Applications/siakadcloud/master/vendor/illuminate/database/Eloquent/Builder.php baris 434"),
     *                          ),
     *                      ),
     *              ),
     *              @OA\Property(property="debug", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="query", type="string", example="select * from ak_mahasiswa where ak_mahasiswa.id = 1 limit 1"),
     *                      @OA\Property(property="time", type="integer", example=2.25),
     *                  ),
     *              ),
     *          ),
     *     ),
     * )
     */

    /**
     * @OA\Post(
     *     path="/v1/mahasiswa-pt",
     *     summary="Add Mahasiswa pt",
     *     tags={"Mahasiswa pt"},
     *     security={{"bearerAuth": {}}},
     *     @OA\RequestBody(
     *         @OA\MediaType(
     *             mediaType="application/json",
     *             @OA\Schema(
     *                 @OA\Property(property="id_mahasiswa", type="integer", example=""),
     *                 @OA\Property(property="nim", type="string", example=""),
     *                 @OA\Property(property="id_periode", type="integer", example=""),
     *                 @OA\Property(property="id_unit", type="integer", example=""),
     *                 @OA\Property(property="id_tahun", type="integer", example=""),
     *                 @OA\Property(property="id_jalur", type="integer", example=""),
     *                 @OA\Property(property="id_gelombang", type="integer", example=""),
     *                 @OA\Property(property="id_sistem", type="integer", example=""),
     *                 @OA\Property(property="id_kelas", type="integer", example=""),
     *                 @OA\Property(property="id_bidang", type="integer", example=""),
     *                 @OA\Property(property="id_periode_akhir", type="integer", example=""),
     *                 @OA\Property(property="email_kampus", type="string", example=""),
     *                 @OA\Property(property="tgl_daftar", type="date", example=""),
     *                 @OA\Property(property="nilai_tpa", type="decimal", example=""),
     *                 @OA\Property(property="nilai_kesehatan", type="decimal", example=""),
     *                 @OA\Property(property="nilai_psikotes", type="decimal", example=""),
     *                 @OA\Property(property="nilai_wawancara", type="decimal", example=""),
     *                 @OA\Property(property="jenis_transfer", type="string", example=""),
     *                 @OA\Property(property="kode_transfer", type="string", example=""),
     *                 @OA\Property(property="kode_pendidikan_asal", type="string", example=""),
     *                 @OA\Property(property="asal_smu", type="string", example=""),
     *                 @OA\Property(property="alamat_smu", type="string", example=""),
     *                 @OA\Property(property="telepon_smu", type="string", example=""),
     *                 @OA\Property(property="jurusan_smu", type="string", example=""),
     *                 @OA\Property(property="thn_lulus_smu", type="integer", example=""),
     *                 @OA\Property(property="nem_smu", type="decimal", example=""),
     *                 @OA\Property(property="no_ijasah_smu", type="string", example=""),
     *                 @OA\Property(property="nisn", type="string", example=""),
     *                 @OA\Property(property="nupn", type="string", example=""),
     *                 @OA\Property(property="id_kota_smu", type="integer", example=""),
     *                 @OA\Property(property="id_propinsi_smu", type="integer", example=""),
     *                 @OA\Property(property="tgl_transfer", type="date", example=""),
     *                 @OA\Property(property="nim_lama", type="string", example=""),
     *                 @OA\Property(property="asal_pt", type="string", example=""),
     *                 @OA\Property(property="prodi_pt", type="string", example=""),
     *                 @OA\Property(property="nim_pt", type="string", example=""),
     *                 @OA\Property(property="ipk_asal", type="decimal", example=""),
     *                 @OA\Property(property="sks_asal", type="integer", example=""),
     *                 @OA\Property(property="npsn", type="string", example=""),
     *                 @OA\Property(property="id_periode_transfer", type="integer", example=""),
     *                 @OA\Property(property="id_unit_asal", type="integer", example=""),
     *                 @OA\Property(property="id_tahun_asal", type="integer", example=""),
     *                 @OA\Property(property="id_universitas", type="integer", example=""),
     *                 @OA\Property(property="id_universitas_prodi", type="integer", example=""),
     *                 @OA\Property(property="nirm", type="string", example=""),
     *                 @OA\Property(property="nirl", type="string", example=""),
     *                 @OA\Property(property="id_almamater", type="integer", example=""),
     *                 @OA\Property(property="is_valid_email", type="string", example=""),
     *                 @OA\Property(property="id_file_transkrip_asal", type="guid", example=""),
     *                 @OA\Property(property="id_file_ijazah_akhir", type="guid", example=""),
     *                 @OA\Property(property="id_file_surat_pindah", type="guid", example=""),
     *             )
     *         )
     *     ),
     *     @OA\Response(
     *          response=201,
     *          description="Success add new mahasiswa pt.",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(property="data", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="id", type="integer", example=""),
     *                      @OA\Property(property="id_mahasiswa", type="integer", example=""),
     *                      @OA\Property(property="nim", type="string", example=""),
     *                      @OA\Property(property="id_periode", type="integer", example=""),
     *                      @OA\Property(property="id_unit", type="integer", example=""),
     *                      @OA\Property(property="id_tahun", type="integer", example=""),
     *                      @OA\Property(property="id_jalur", type="integer", example=""),
     *                      @OA\Property(property="id_gelombang", type="integer", example=""),
     *                      @OA\Property(property="id_sistem", type="integer", example=""),
     *                      @OA\Property(property="id_kelas", type="integer", example=""),
     *                      @OA\Property(property="id_bidang", type="integer", example=""),
     *                      @OA\Property(property="id_periode_akhir", type="integer", example=""),
     *                      @OA\Property(property="email_kampus", type="string", example=""),
     *                      @OA\Property(property="tgl_daftar", type="date", example=""),
     *                      @OA\Property(property="nilai_tpa", type="decimal", example=""),
     *                      @OA\Property(property="nilai_kesehatan", type="decimal", example=""),
     *                      @OA\Property(property="nilai_psikotes", type="decimal", example=""),
     *                      @OA\Property(property="nilai_wawancara", type="decimal", example=""),
     *                      @OA\Property(property="jenis_transfer", type="string", example=""),
     *                      @OA\Property(property="kode_transfer", type="string", example=""),
     *                      @OA\Property(property="kode_pendidikan_asal", type="string", example=""),
     *                      @OA\Property(property="asal_smu", type="string", example=""),
     *                      @OA\Property(property="alamat_smu", type="string", example=""),
     *                      @OA\Property(property="telepon_smu", type="string", example=""),
     *                      @OA\Property(property="jurusan_smu", type="string", example=""),
     *                      @OA\Property(property="thn_lulus_smu", type="integer", example=""),
     *                      @OA\Property(property="nem_smu", type="decimal", example=""),
     *                      @OA\Property(property="no_ijasah_smu", type="string", example=""),
     *                      @OA\Property(property="nisn", type="string", example=""),
     *                      @OA\Property(property="nupn", type="string", example=""),
     *                      @OA\Property(property="id_kota_smu", type="integer", example=""),
     *                      @OA\Property(property="id_propinsi_smu", type="integer", example=""),
     *                      @OA\Property(property="tgl_transfer", type="date", example=""),
     *                      @OA\Property(property="nim_lama", type="string", example=""),
     *                      @OA\Property(property="asal_pt", type="string", example=""),
     *                      @OA\Property(property="prodi_pt", type="string", example=""),
     *                      @OA\Property(property="nim_pt", type="string", example=""),
     *                      @OA\Property(property="ipk_asal", type="decimal", example=""),
     *                      @OA\Property(property="sks_asal", type="integer", example=""),
     *                      @OA\Property(property="npsn", type="string", example=""),
     *                      @OA\Property(property="id_periode_transfer", type="integer", example=""),
     *                      @OA\Property(property="id_unit_asal", type="integer", example=""),
     *                      @OA\Property(property="id_tahun_asal", type="integer", example=""),
     *                      @OA\Property(property="id_universitas", type="integer", example=""),
     *                      @OA\Property(property="id_universitas_prodi", type="integer", example=""),
     *                      @OA\Property(property="nirm", type="string", example=""),
     *                      @OA\Property(property="nirl", type="string", example=""),
     *                      @OA\Property(property="id_almamater", type="integer", example=""),
     *                      @OA\Property(property="is_valid_email", type="string", example=""),
     *                      @OA\Property(property="id_file_transkrip_asal", type="guid", example=""),
     *                      @OA\Property(property="id_file_ijazah_akhir", type="guid", example=""),
     *                      @OA\Property(property="id_file_surat_pindah", type="guid", example=""),
     *                  ),
     *              ),
     *              @OA\Property(property="debug", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="query", type="string", example="insert into ak_mahasiswa_pt () values () returning id"),
     *                      @OA\Property(property="time", type="integer", example=8.13),
     *                  ),
     *              ),
     *          ),
     *     ),
     *     @OA\Response(response=400, description="Bad Request",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(property="error", type="object",
     *                      @OA\Property(property="code", type="integer", example=400),
     *                      @OA\Property(property="message", type="string", example="Data yang dikirimkan tidak valid"),
     *                      @OA\Property(property="validation", type="object",
     *                          @OA\Property(property="nama_field", type="array",
     *                              @OA\Items(type="string", example="Harus diisi"),
     *                          ),
     *                      ),
     *              ),
     *          ),
     *     ),
     * )
     */

    /**
     * @OA\Put(
     *     path="/v1/mahasiswa-pt/{id}",
     *     summary="Update mahasiswa pt",
     *     tags={"Mahasiswa pt"},
     *     security={{"bearerAuth": {}}},
     *     @OA\Parameter(
     *         description="id mahasiswa pt",
     *         in="path",
     *         name="id",
     *         required=true,
     *         @OA\Schema(type="integer"),
     *         @OA\Examples(example="int", value="1", summary="An int value."),
     *     ),
     *     @OA\RequestBody(
     *         @OA\MediaType(
     *             mediaType="application/json",
     *             @OA\Schema(
     *                 @OA\Property(property="id_mahasiswa", type="integer", example=""),
     *                 @OA\Property(property="nim", type="string", example=""),
     *                 @OA\Property(property="id_periode", type="integer", example=""),
     *                 @OA\Property(property="id_unit", type="integer", example=""),
     *                 @OA\Property(property="id_tahun", type="integer", example=""),
     *                 @OA\Property(property="id_jalur", type="integer", example=""),
     *                 @OA\Property(property="id_gelombang", type="integer", example=""),
     *                 @OA\Property(property="id_sistem", type="integer", example=""),
     *                 @OA\Property(property="id_kelas", type="integer", example=""),
     *                 @OA\Property(property="id_bidang", type="integer", example=""),
     *                 @OA\Property(property="id_periode_akhir", type="integer", example=""),
     *                 @OA\Property(property="email_kampus", type="string", example=""),
     *                 @OA\Property(property="tgl_daftar", type="date", example=""),
     *                 @OA\Property(property="nilai_tpa", type="decimal", example=""),
     *                 @OA\Property(property="nilai_kesehatan", type="decimal", example=""),
     *                 @OA\Property(property="nilai_psikotes", type="decimal", example=""),
     *                 @OA\Property(property="nilai_wawancara", type="decimal", example=""),
     *                 @OA\Property(property="jenis_transfer", type="string", example=""),
     *                 @OA\Property(property="kode_transfer", type="string", example=""),
     *                 @OA\Property(property="kode_pendidikan_asal", type="string", example=""),
     *                 @OA\Property(property="asal_smu", type="string", example=""),
     *                 @OA\Property(property="alamat_smu", type="string", example=""),
     *                 @OA\Property(property="telepon_smu", type="string", example=""),
     *                 @OA\Property(property="jurusan_smu", type="string", example=""),
     *                 @OA\Property(property="thn_lulus_smu", type="integer", example=""),
     *                 @OA\Property(property="nem_smu", type="decimal", example=""),
     *                 @OA\Property(property="no_ijasah_smu", type="string", example=""),
     *                 @OA\Property(property="nisn", type="string", example=""),
     *                 @OA\Property(property="nupn", type="string", example=""),
     *                 @OA\Property(property="id_kota_smu", type="integer", example=""),
     *                 @OA\Property(property="id_propinsi_smu", type="integer", example=""),
     *                 @OA\Property(property="tgl_transfer", type="date", example=""),
     *                 @OA\Property(property="nim_lama", type="string", example=""),
     *                 @OA\Property(property="asal_pt", type="string", example=""),
     *                 @OA\Property(property="prodi_pt", type="string", example=""),
     *                 @OA\Property(property="nim_pt", type="string", example=""),
     *                 @OA\Property(property="ipk_asal", type="decimal", example=""),
     *                 @OA\Property(property="sks_asal", type="integer", example=""),
     *                 @OA\Property(property="npsn", type="string", example=""),
     *                 @OA\Property(property="id_periode_transfer", type="integer", example=""),
     *                 @OA\Property(property="id_unit_asal", type="integer", example=""),
     *                 @OA\Property(property="id_tahun_asal", type="integer", example=""),
     *                 @OA\Property(property="id_universitas", type="integer", example=""),
     *                 @OA\Property(property="id_universitas_prodi", type="integer", example=""),
     *                 @OA\Property(property="nirm", type="string", example=""),
     *                 @OA\Property(property="nirl", type="string", example=""),
     *                 @OA\Property(property="id_almamater", type="integer", example=""),
     *                 @OA\Property(property="is_valid_email", type="string", example=""),
     *                 @OA\Property(property="id_file_transkrip_asal", type="guid", example=""),
     *                 @OA\Property(property="id_file_ijazah_akhir", type="guid", example=""),
     *                 @OA\Property(property="id_file_surat_pindah", type="guid", example=""),
     *             )
     *         )
     *     ),
     *     @OA\Response(
     *          response=200,
     *          description="Success Update Mahasiswa pt.",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(property="data", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="id", type="integer", example=""),
     *                      @OA\Property(property="id_mahasiswa", type="integer", example=""),
     *                      @OA\Property(property="nim", type="string", example=""),
     *                      @OA\Property(property="id_periode", type="integer", example=""),
     *                      @OA\Property(property="id_unit", type="integer", example=""),
     *                      @OA\Property(property="id_tahun", type="integer", example=""),
     *                      @OA\Property(property="id_jalur", type="integer", example=""),
     *                      @OA\Property(property="id_gelombang", type="integer", example=""),
     *                      @OA\Property(property="id_sistem", type="integer", example=""),
     *                      @OA\Property(property="id_kelas", type="integer", example=""),
     *                      @OA\Property(property="id_bidang", type="integer", example=""),
     *                      @OA\Property(property="id_periode_akhir", type="integer", example=""),
     *                      @OA\Property(property="email_kampus", type="string", example=""),
     *                      @OA\Property(property="tgl_daftar", type="date", example=""),
     *                      @OA\Property(property="nilai_tpa", type="decimal", example=""),
     *                      @OA\Property(property="nilai_kesehatan", type="decimal", example=""),
     *                      @OA\Property(property="nilai_psikotes", type="decimal", example=""),
     *                      @OA\Property(property="nilai_wawancara", type="decimal", example=""),
     *                      @OA\Property(property="jenis_transfer", type="string", example=""),
     *                      @OA\Property(property="kode_transfer", type="string", example=""),
     *                      @OA\Property(property="kode_pendidikan_asal", type="string", example=""),
     *                      @OA\Property(property="asal_smu", type="string", example=""),
     *                      @OA\Property(property="alamat_smu", type="string", example=""),
     *                      @OA\Property(property="telepon_smu", type="string", example=""),
     *                      @OA\Property(property="jurusan_smu", type="string", example=""),
     *                      @OA\Property(property="thn_lulus_smu", type="integer", example=""),
     *                      @OA\Property(property="nem_smu", type="decimal", example=""),
     *                      @OA\Property(property="no_ijasah_smu", type="string", example=""),
     *                      @OA\Property(property="nisn", type="string", example=""),
     *                      @OA\Property(property="nupn", type="string", example=""),
     *                      @OA\Property(property="id_kota_smu", type="integer", example=""),
     *                      @OA\Property(property="id_propinsi_smu", type="integer", example=""),
     *                      @OA\Property(property="tgl_transfer", type="date", example=""),
     *                      @OA\Property(property="nim_lama", type="string", example=""),
     *                      @OA\Property(property="asal_pt", type="string", example=""),
     *                      @OA\Property(property="prodi_pt", type="string", example=""),
     *                      @OA\Property(property="nim_pt", type="string", example=""),
     *                      @OA\Property(property="ipk_asal", type="decimal", example=""),
     *                      @OA\Property(property="sks_asal", type="integer", example=""),
     *                      @OA\Property(property="npsn", type="string", example=""),
     *                      @OA\Property(property="id_periode_transfer", type="integer", example=""),
     *                      @OA\Property(property="id_unit_asal", type="integer", example=""),
     *                      @OA\Property(property="id_tahun_asal", type="integer", example=""),
     *                      @OA\Property(property="id_universitas", type="integer", example=""),
     *                      @OA\Property(property="id_universitas_prodi", type="integer", example=""),
     *                      @OA\Property(property="nirm", type="string", example=""),
     *                      @OA\Property(property="nirl", type="string", example=""),
     *                      @OA\Property(property="id_almamater", type="integer", example=""),
     *                      @OA\Property(property="is_valid_email", type="string", example=""),
     *                      @OA\Property(property="id_file_transkrip_asal", type="guid", example=""),
     *                      @OA\Property(property="id_file_ijazah_akhir", type="guid", example=""),
     *                      @OA\Property(property="id_file_surat_pindah", type="guid", example=""),
     *                  ),
     *              ),
     *              @OA\Property(property="debug", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="query", type="string", example="update ak_mahasiswa_pt set ak_mahasiswa_pt.id = 1 where ak_mahasiswa_pt.id = 1"),
     *                      @OA\Property(property="time", type="integer", example=8.13),
     *                  ),
     *              ),
     *          ),
     *       ),
     *     @OA\Response(response=404, description="Error: Not Found",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(property="error", type="object",
     *                      @OA\Property(property="code", type="integer", example=404),
     *                      @OA\Property(property="message", type="string", example="Data tidak ditemukan"),
     *                      @OA\Property(property="debug", type="object",
     *                          @OA\Property(property="message", type="string", example="No query results for model [App\Models\MahasiswaPt] 1"),
     *                          @OA\Property(property="files", type="object",
     *                              @OA\Property(type="string", example="/Users/brondol/Applications/siakadcloud/master/vendor/illuminate/database/Eloquent/Builder.php baris 434"),
     *                          ),
     *                      ),
     *              ),
     *              @OA\Property(property="debug", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="query", type="string", example="select * from ak_mahasiswa where ak_mahasiswa.id = 1 limit 1"),
     *                      @OA\Property(property="time", type="integer", example=2.25),
     *                  ),
     *              ),
     *          ),
     *     ),
     * )
     */

    /**
     * @OA\Delete(
     *     path="/v1/mahasiswa-pt/{id}",
     *     summary="Delete mahasiswa pt",
     *     tags={"Mahasiswa pt"},
     *     security={{"bearerAuth": {}}},
     *     @OA\Parameter(
     *         description="id mahasiswa pt",
     *         in="path",
     *         name="id",
     *         required=true,
     *         @OA\Schema(type="integer"),
     *         @OA\Examples(example="int", value="1", summary="An int value."),
     *     ),
     *     @OA\Response(
     *          response=200,
     *          description="Berhasil Menghapus Mahasiswa pt"
     *       ),
     *     @OA\Response(response=404, description="Error: Not Found",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(property="error", type="object",
     *                      @OA\Property(property="code", type="integer", example=404),
     *                      @OA\Property(property="message", type="string", example="Data tidak ditemukan"),
     *                      @OA\Property(property="debug", type="object",
     *                          @OA\Property(property="message", type="string", example="No query results for model [App\Models\MahasiswaPt] 1"),
     *                          @OA\Property(property="files", type="object",
     *                              @OA\Property(type="string", example="/Users/brondol/Applications/siakadcloud/master/vendor/illuminate/database/Eloquent/Builder.php baris 434"),
     *                          ),
     *                      ),
     *              ),
     *              @OA\Property(property="debug", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="query", type="string", example="select * from ak_mahasiswa where ak_mahasiswa.id = 1 limit 1"),
     *                      @OA\Property(property="time", type="integer", example=2.25),
     *                  ),
     *              ),
     *          ),
     *     ),
     * )
     */

    /**
     *     @OA\Schema(
     *         schema="Mahasiswa pt",
     *         @OA\Xml(name="Mahasiswa pt"),
     *         @OA\Property(property="id", type="integer", example=""),
     *         @OA\Property(property="id_mahasiswa", type="integer", example=""),
     *         @OA\Property(property="nim", type="string", example=""),
     *         @OA\Property(property="id_periode", type="integer", example=""),
     *         @OA\Property(property="id_unit", type="integer", example=""),
     *         @OA\Property(property="id_tahun", type="integer", example=""),
     *         @OA\Property(property="id_jalur", type="integer", example=""),
     *         @OA\Property(property="id_gelombang", type="integer", example=""),
     *         @OA\Property(property="id_sistem", type="integer", example=""),
     *         @OA\Property(property="id_kelas", type="integer", example=""),
     *         @OA\Property(property="id_bidang", type="integer", example=""),
     *         @OA\Property(property="id_periode_akhir", type="integer", example=""),
     *         @OA\Property(property="email_kampus", type="string", example=""),
     *         @OA\Property(property="tgl_daftar", type="date", example=""),
     *         @OA\Property(property="nilai_tpa", type="decimal", example=""),
     *         @OA\Property(property="nilai_kesehatan", type="decimal", example=""),
     *         @OA\Property(property="nilai_psikotes", type="decimal", example=""),
     *         @OA\Property(property="nilai_wawancara", type="decimal", example=""),
     *         @OA\Property(property="jenis_transfer", type="string", example=""),
     *         @OA\Property(property="kode_transfer", type="string", example=""),
     *         @OA\Property(property="kode_pendidikan_asal", type="string", example=""),
     *         @OA\Property(property="asal_smu", type="string", example=""),
     *         @OA\Property(property="alamat_smu", type="string", example=""),
     *         @OA\Property(property="telepon_smu", type="string", example=""),
     *         @OA\Property(property="jurusan_smu", type="string", example=""),
     *         @OA\Property(property="thn_lulus_smu", type="integer", example=""),
     *         @OA\Property(property="nem_smu", type="decimal", example=""),
     *         @OA\Property(property="no_ijasah_smu", type="string", example=""),
     *         @OA\Property(property="nisn", type="string", example=""),
     *         @OA\Property(property="nupn", type="string", example=""),
     *         @OA\Property(property="id_kota_smu", type="integer", example=""),
     *         @OA\Property(property="id_propinsi_smu", type="integer", example=""),
     *         @OA\Property(property="tgl_transfer", type="date", example=""),
     *         @OA\Property(property="nim_lama", type="string", example=""),
     *         @OA\Property(property="asal_pt", type="string", example=""),
     *         @OA\Property(property="prodi_pt", type="string", example=""),
     *         @OA\Property(property="nim_pt", type="string", example=""),
     *         @OA\Property(property="ipk_asal", type="decimal", example=""),
     *         @OA\Property(property="sks_asal", type="integer", example=""),
     *         @OA\Property(property="npsn", type="string", example=""),
     *         @OA\Property(property="id_periode_transfer", type="integer", example=""),
     *         @OA\Property(property="id_unit_asal", type="integer", example=""),
     *         @OA\Property(property="id_tahun_asal", type="integer", example=""),
     *         @OA\Property(property="id_universitas", type="integer", example=""),
     *         @OA\Property(property="id_universitas_prodi", type="integer", example=""),
     *         @OA\Property(property="nirm", type="string", example=""),
     *         @OA\Property(property="nirl", type="string", example=""),
     *         @OA\Property(property="id_almamater", type="integer", example=""),
     *         @OA\Property(property="is_valid_email", type="string", example=""),
     *         @OA\Property(property="id_file_transkrip_asal", type="guid", example=""),
     *         @OA\Property(property="id_file_ijazah_akhir", type="guid", example=""),
     *         @OA\Property(property="id_file_surat_pindah", type="guid", example=""),
     *     ),
     */
}
        