<?php

namespace App\Http\Controllers\V1;

use Siakad\Controller;

class MahasiswaController extends Controller
{
    /**
     *
     * @OA\Get(
     *      path="/v1/mahasiswa",
     *      tags={"Mahasiswa"},
     *      summary="List Mahasiswa",
     *      security={{"bearerAuth": {}}},
     *      @OA\Response(
     *          response=200,
     *          description="Get list of mahasiswa.",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(property="data", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="id", type="integer", example=1),
     *                      @OA\Property(property="nama", type="string", example="Aulia Ahmad Nabil"),
     *                      @OA\Property(property="gelar_depan", type="string", example="H."),
     *                      @OA\Property(property="gelar_belakang", type="string", example="S. Kom."),
     *                      @OA\Property(property="jenis_kelamin", type="string", example="L"),
     *                      @OA\Property(property="tempat_lahir", type="string", example="Bandar Lampung"),
     *                      @OA\Property(property="tgl_lahir", type="date", example="2000-05-10"),
     *                      @OA\Property(property="alamat", type="string", example="Perumahan Nusan"),
     *                      @OA\Property(property="telepon", type="string", example="0721"),
     *                      @OA\Property(property="hp", type="string", example="082222222222"),
     *                      @OA\Property(property="hp_2", type="string", example="08961234567"),
     *                      @OA\Property(property="email", type="string", example="nabilunited2@gmail.com"),
     *                      @OA\Property(property="gol_darah", type="string", example="O"),
     *                      @OA\Property(property="status_nikah", type="string", example="B"),
     *                      @OA\Property(property="nik", type="string", example="1871051005000099"),
     *                      @OA\Property(property="no_kk", type="string", example="18710510004211"),
     *                      @OA\Property(property="rt", type="string", example="02"),
     *                      @OA\Property(property="rw", type="string", example="02"),
     *                      @OA\Property(property="dusun", type="string", example="konoha"),
     *                      @OA\Property(property="desa", type="string", example="durian runtuh"),
     *                      @OA\Property(property="no_kps", type="string", example="281101010101"),
     *                      @OA\Property(property="id_agama", type="integer", example=1),
     *                      @OA\Property(property="id_negara", type="integer", example=1),
     *                      @OA\Property(property="id_kota", type="integer", example=1),
     *                      @OA\Property(property="id_kecamatan", type="integer", example=1),
     *                      @OA\Property(property="id_suku", type="integer", example=1),
     *                      @OA\Property(property="id_pekerjaan", type="integer", example=1),
     *                      @OA\Property(property="id_penghasilan", type="integer", example=1),
     *                      @OA\Property(property="id_tinggal", type="integer", example=1),
     *                      @OA\Property(property="id_transport", type="integer", example=1),
     *                      @OA\Property(property="id_hobi", type="integer", example=1),
     *                      @OA\Property(property="id_minat", type="integer", example=1),
     *                      @OA\Property(property="no_rekening", type="string", example="18710510004211"),
     *                      @OA\Property(property="berat_badan", type="string", example="72"),
     *                      @OA\Property(property="tinggi_badan", type="string", example="173"),
     *                      @OA\Property(property="instansi_kerja", type="string", example="Universitas Lampung"),
     *                      @OA\Property(property="email_ortu", type="string", example="mujiyono@gmail.com"),
     *                      @OA\Property(property="show_hp", type="string", example="1"),
     *                      @OA\Property(property="show_kota", type="string", example="1"),
     *                      @OA\Property(property="show_hobi", type="string", example="1"),
     *                      @OA\Property(property="show_minat", type="string", example="1"),
     *                      @OA\Property(property="is_valid_email", type="string", example="1"),
     *                      @OA\Property(property="id_file_akta_kelahiran", type="guid", example="2e7b8f7c-b8f7-4f0f-b8e2-c8f8f8f8f8f8"),
     *                  ),
     *              ),
     *              @OA\Property(property="info", type="object",
     *                      @OA\Property(property="total", type="integer", example=10),
     *                      @OA\Property(property="page", type="integer", example=1),
     *                      @OA\Property(property="last_page", type="integer", example=1),
     *                      @OA\Property(property="count", type="integer", example=10),
     *                      @OA\Property(property="start", type="integer", example=1),
     *                      @OA\Property(property="end", type="integer", example=10),
     *              ),
     *              @OA\Property(property="debug", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="query", type="string", example="select count(*) as aggregate from ak_mahasiswa"),
     *                      @OA\Property(property="time", type="integer", example=59.0),
     *                  ),
     *              ),
     *          ),
     *       ),
     * )
     */

    /**
     * @OA\Get(
     *     path="/v1/mahasiswa/{id}",
     *     summary="Data Mahasiswa",
     *     tags={"Mahasiswa"},
     *     security={{"bearerAuth": {}}},
     *     @OA\Parameter(
     *         description="id mahasiswa",
     *         in="path",
     *         name="id",
     *         required=true,
     *         @OA\Schema(type="integer"),
     *         @OA\Examples(example="int", value="1", summary="An int value."),
     *     ),
     *     @OA\Response(
     *          response=200,
     *          description="Get data of mahasiswa.",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(property="data", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="id", type="integer", example=1),
     *                      @OA\Property(property="nama", type="string", example="Aulia Ahmad Nabil"),
     *                      @OA\Property(property="gelar_depan", type="string", example="H."),
     *                      @OA\Property(property="gelar_belakang", type="string", example="S. Kom."),
     *                      @OA\Property(property="jenis_kelamin", type="string", example="L"),
     *                      @OA\Property(property="tempat_lahir", type="string", example="Bandar Lampung"),
     *                      @OA\Property(property="tgl_lahir", type="date", example="2000-05-10"),
     *                      @OA\Property(property="alamat", type="string", example="Perumahan Nusan"),
     *                      @OA\Property(property="telepon", type="string", example="0721"),
     *                      @OA\Property(property="hp", type="string", example="082222222222"),
     *                      @OA\Property(property="hp_2", type="string", example="08961234567"),
     *                      @OA\Property(property="email", type="string", example="nabilunited2@gmail.com"),
     *                      @OA\Property(property="gol_darah", type="string", example="O"),
     *                      @OA\Property(property="status_nikah", type="string", example="B"),
     *                      @OA\Property(property="nik", type="string", example="1871051005000099"),
     *                      @OA\Property(property="no_kk", type="string", example="18710510004211"),
     *                      @OA\Property(property="rt", type="string", example="02"),
     *                      @OA\Property(property="rw", type="string", example="02"),
     *                      @OA\Property(property="dusun", type="string", example="konoha"),
     *                      @OA\Property(property="desa", type="string", example="durian runtuh"),
     *                      @OA\Property(property="no_kps", type="string", example="281101010101"),
     *                      @OA\Property(property="id_agama", type="integer", example=1),
     *                      @OA\Property(property="id_negara", type="integer", example=1),
     *                      @OA\Property(property="id_kota", type="integer", example=1),
     *                      @OA\Property(property="id_kecamatan", type="integer", example=1),
     *                      @OA\Property(property="id_suku", type="integer", example=1),
     *                      @OA\Property(property="id_pekerjaan", type="integer", example=1),
     *                      @OA\Property(property="id_penghasilan", type="integer", example=1),
     *                      @OA\Property(property="id_tinggal", type="integer", example=1),
     *                      @OA\Property(property="id_transport", type="integer", example=1),
     *                      @OA\Property(property="id_hobi", type="integer", example=1),
     *                      @OA\Property(property="id_minat", type="integer", example=1),
     *                      @OA\Property(property="no_rekening", type="string", example="18710510004211"),
     *                      @OA\Property(property="berat_badan", type="string", example="72"),
     *                      @OA\Property(property="tinggi_badan", type="string", example="173"),
     *                      @OA\Property(property="instansi_kerja", type="string", example="Universitas Lampung"),
     *                      @OA\Property(property="email_ortu", type="string", example="mujiyono@gmail.com"),
     *                      @OA\Property(property="show_hp", type="string", example="1"),
     *                      @OA\Property(property="show_kota", type="string", example="1"),
     *                      @OA\Property(property="show_hobi", type="string", example="1"),
     *                      @OA\Property(property="show_minat", type="string", example="1"),
     *                      @OA\Property(property="is_valid_email", type="string", example="1"),
     *                      @OA\Property(property="id_file_akta_kelahiran", type="guid", example="2e7b8f7c-b8f7-4f0f-b8e2-c8f8f8f8f8f8"),
     *                  ),
     *              ),
     *              @OA\Property(property="debug", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="query", type="string", example="SELECT * FROM ak_mahasiswa WHERE ak_mahasiswa.id = 1 limit 1"),
     *                      @OA\Property(property="time", type="integer", example=59.0),
     *                  ),
     *              ),
     *          ),
     *     ),
     *     @OA\Response(response=404, description="Error: Not Found",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(property="error", type="object",
     *                      @OA\Property(property="code", type="integer", example=404),
     *                      @OA\Property(property="message", type="string", example="Data tidak ditemukan"),
     *                      @OA\Property(property="debug", type="object",
     *                          @OA\Property(property="message", type="string", example="No query results for model [App\Models\Mahasiswa] 1"),
     *                          @OA\Property(property="files", type="object",
     *                              @OA\Property(type="string", example="/Users/brondol/Applications/siakadcloud/master/vendor/illuminate/database/Eloquent/Builder.php baris 434"),
     *                          ),
     *                      ),
     *              ),
     *              @OA\Property(property="debug", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="query", type="string", example="select * from ak_mahasiswa where ak_mahasiswa.id = 1 limit 1"),
     *                      @OA\Property(property="time", type="integer", example=2.25),
     *                  ),
     *              ),
     *          ),
     *     ),
     * )
     */

    /**
     * @OA\Post(
     *     path="/v1/mahasiswa",
     *     summary="Add Mahasiswa",
     *     tags={"Mahasiswa"},
     *     security={{"bearerAuth": {}}},
     *     @OA\RequestBody(
     *         @OA\MediaType(
     *             mediaType="application/json",
     *             @OA\Schema(
     * required={"nama", "jenis_kelamin", "tempat_lahir", "tgl_lahir", "show_hp", "show_kota", "show_hobi", "show_minat", "is_valid_email"},
     *                 @OA\Property(property="nama", type="string", example="Aulia Ahmad Nabil"),
     *                 @OA\Property(property="gelar_depan", type="string", example="H."),
     *                 @OA\Property(property="gelar_belakang", type="string", example="S. Kom."),
     *                 @OA\Property(property="jenis_kelamin", type="string", example="L"),
     *                 @OA\Property(property="tempat_lahir", type="string", example="Bandar Lampung"),
     *                 @OA\Property(property="tgl_lahir", type="date", example="2000-05-10"),
     *                 @OA\Property(property="alamat", type="string", example="Perumahan Nusan"),
     *                 @OA\Property(property="telepon", type="string", example="0721"),
     *                 @OA\Property(property="hp", type="string", example="082222222222"),
     *                 @OA\Property(property="hp_2", type="string", example="08961234567"),
     *                 @OA\Property(property="email", type="string", example="nabilunited2@gmail.com"),
     *                 @OA\Property(property="gol_darah", type="string", example="O"),
     *                 @OA\Property(property="status_nikah", type="string", example="B"),
     *                 @OA\Property(property="nik", type="string", example="1871051005000099"),
     *                 @OA\Property(property="no_kk", type="string", example="18710510004211"),
     *                 @OA\Property(property="rt", type="string", example="02"),
     *                 @OA\Property(property="rw", type="string", example="02"),
     *                 @OA\Property(property="dusun", type="string", example="konoha"),
     *                 @OA\Property(property="desa", type="string", example="durian runtuh"),
     *                 @OA\Property(property="no_kps", type="string", example="281101010101"),
     *                 @OA\Property(property="id_agama", type="integer", example=1),
     *                 @OA\Property(property="id_negara", type="integer", example=1),
     *                 @OA\Property(property="id_kota", type="integer", example=1),
     *                 @OA\Property(property="id_kecamatan", type="integer", example=1),
     *                 @OA\Property(property="id_suku", type="integer", example=1),
     *                 @OA\Property(property="id_pekerjaan", type="integer", example=1),
     *                 @OA\Property(property="id_penghasilan", type="integer", example=1),
     *                 @OA\Property(property="id_tinggal", type="integer", example=1),
     *                 @OA\Property(property="id_transport", type="integer", example=1),
     *                 @OA\Property(property="id_hobi", type="integer", example=1),
     *                 @OA\Property(property="id_minat", type="integer", example=1),
     *                 @OA\Property(property="no_rekening", type="string", example="18710510004211"),
     *                 @OA\Property(property="berat_badan", type="string", example="72"),
     *                 @OA\Property(property="tinggi_badan", type="string", example="173"),
     *                 @OA\Property(property="instansi_kerja", type="string", example="Universitas Lampung"),
     *                 @OA\Property(property="email_ortu", type="string", example="mujiyono@gmail.com"),
     *                 @OA\Property(property="show_hp", type="string", example="1"),
     *                 @OA\Property(property="show_kota", type="string", example="1"),
     *                 @OA\Property(property="show_hobi", type="string", example="1"),
     *                 @OA\Property(property="show_minat", type="string", example="1"),
     *                 @OA\Property(property="is_valid_email", type="string", example="1"),
     *             )
     *         )
     *     ),
     *     @OA\Response(
     *          response=201,
     *          description="Success add new mahasiswa.",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(property="data", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="id", type="integer", example=1),
     *                      @OA\Property(property="nama", type="string", example="Aulia Ahmad Nabil"),
     *                      @OA\Property(property="gelar_depan", type="string", example="H."),
     *                      @OA\Property(property="gelar_belakang", type="string", example="S. Kom."),
     *                      @OA\Property(property="jenis_kelamin", type="string", example="L"),
     *                      @OA\Property(property="tempat_lahir", type="string", example="Bandar Lampung"),
     *                      @OA\Property(property="tgl_lahir", type="date", example="2000-05-10"),
     *                      @OA\Property(property="alamat", type="string", example="Perumahan Nusan"),
     *                      @OA\Property(property="telepon", type="string", example="0721"),
     *                      @OA\Property(property="hp", type="string", example="082222222222"),
     *                      @OA\Property(property="hp_2", type="string", example="08961234567"),
     *                      @OA\Property(property="email", type="string", example="nabilunited2@gmail.com"),
     *                      @OA\Property(property="gol_darah", type="string", example="O"),
     *                      @OA\Property(property="status_nikah", type="string", example="B"),
     *                      @OA\Property(property="nik", type="string", example="1871051005000099"),
     *                      @OA\Property(property="no_kk", type="string", example="18710510004211"),
     *                      @OA\Property(property="rt", type="string", example="02"),
     *                      @OA\Property(property="rw", type="string", example="02"),
     *                      @OA\Property(property="dusun", type="string", example="konoha"),
     *                      @OA\Property(property="desa", type="string", example="durian runtuh"),
     *                      @OA\Property(property="no_kps", type="string", example="281101010101"),
     *                      @OA\Property(property="id_agama", type="integer", example=1),
     *                      @OA\Property(property="id_negara", type="integer", example=1),
     *                      @OA\Property(property="id_kota", type="integer", example=1),
     *                      @OA\Property(property="id_kecamatan", type="integer", example=1),
     *                      @OA\Property(property="id_suku", type="integer", example=1),
     *                      @OA\Property(property="id_pekerjaan", type="integer", example=1),
     *                      @OA\Property(property="id_penghasilan", type="integer", example=1),
     *                      @OA\Property(property="id_tinggal", type="integer", example=1),
     *                      @OA\Property(property="id_transport", type="integer", example=1),
     *                      @OA\Property(property="id_hobi", type="integer", example=1),
     *                      @OA\Property(property="id_minat", type="integer", example=1),
     *                      @OA\Property(property="no_rekening", type="string", example="18710510004211"),
     *                      @OA\Property(property="berat_badan", type="string", example="72"),
     *                      @OA\Property(property="tinggi_badan", type="string", example="173"),
     *                      @OA\Property(property="instansi_kerja", type="string", example="Universitas Lampung"),
     *                      @OA\Property(property="email_ortu", type="string", example="mujiyono@gmail.com"),
     *                      @OA\Property(property="show_hp", type="string", example="1"),
     *                      @OA\Property(property="show_kota", type="string", example="1"),
     *                      @OA\Property(property="show_hobi", type="string", example="1"),
     *                      @OA\Property(property="show_minat", type="string", example="1"),
     *                      @OA\Property(property="is_valid_email", type="string", example="1"),
     *                      @OA\Property(property="id_file_akta_kelahiran", type="guid", example="2e7b8f7c-b8f7-4f0f-b8e2-c8f8f8f8f8f8"),
     *                  ),
     *              ),
     *              @OA\Property(property="debug", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="query", type="string", example="insert into ak_mahasiswa () values () returning id"),
     *                      @OA\Property(property="time", type="integer", example=8.13),
     *                  ),
     *              ),
     *          ),
     *     ),
     *     @OA\Response(response=400, description="Bad Request",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(property="error", type="object",
     *                      @OA\Property(property="code", type="integer", example=400),
     *                      @OA\Property(property="message", type="string", example="Data yang dikirimkan tidak valid"),
     *                      @OA\Property(property="validation", type="object",
     *                          @OA\Property(property="nama_field", type="array",
     *                              @OA\Items(type="string", example="Harus diisi"),
     *                          ),
     *                      ),
     *              ),
     *          ),
     *     ),
     * )
     */

    /**
     * @OA\Put(
     *     path="/v1/mahasiswa/{id}",
     *     summary="Update mahasiswa",
     *     tags={"Mahasiswa"},
     *     security={{"bearerAuth": {}}},
     *     @OA\Parameter(
     *         description="id mahasiswa",
     *         in="path",
     *         name="id",
     *         required=true,
     *         @OA\Schema(type="integer"),
     *         @OA\Examples(example="int", value="1", summary="An int value."),
     *     ),
     *     @OA\RequestBody(
     *         @OA\MediaType(
     *             mediaType="application/json",
     *             @OA\Schema(
     *                 @OA\Property(property="nama", type="string", example="Aulia Ahmad Nabil"),
     *                 @OA\Property(property="gelar_depan", type="string", example="H."),
     *                 @OA\Property(property="gelar_belakang", type="string", example="S. Kom."),
     *                 @OA\Property(property="jenis_kelamin", type="string", example="L"),
     *                 @OA\Property(property="tempat_lahir", type="string", example="Bandar Lampung"),
     *                 @OA\Property(property="tgl_lahir", type="date", example="2000-05-10"),
     *                 @OA\Property(property="alamat", type="string", example="Perumahan Nusan"),
     *                 @OA\Property(property="telepon", type="string", example="0721"),
     *                 @OA\Property(property="hp", type="string", example="082222222222"),
     *                 @OA\Property(property="hp_2", type="string", example="08961234567"),
     *                 @OA\Property(property="email", type="string", example="nabilunited2@gmail.com"),
     *                 @OA\Property(property="gol_darah", type="string", example="O"),
     *                 @OA\Property(property="status_nikah", type="string", example="B"),
     *                 @OA\Property(property="nik", type="string", example="1871051005000099"),
     *                 @OA\Property(property="no_kk", type="string", example="18710510004211"),
     *                 @OA\Property(property="rt", type="string", example="02"),
     *                 @OA\Property(property="rw", type="string", example="02"),
     *                 @OA\Property(property="dusun", type="string", example="konoha"),
     *                 @OA\Property(property="desa", type="string", example="durian runtuh"),
     *                 @OA\Property(property="no_kps", type="string", example="281101010101"),
     *                 @OA\Property(property="id_agama", type="integer", example=1),
     *                 @OA\Property(property="id_negara", type="integer", example=1),
     *                 @OA\Property(property="id_kota", type="integer", example=1),
     *                 @OA\Property(property="id_kecamatan", type="integer", example=1),
     *                 @OA\Property(property="id_suku", type="integer", example=1),
     *                 @OA\Property(property="id_pekerjaan", type="integer", example=1),
     *                 @OA\Property(property="id_penghasilan", type="integer", example=1),
     *                 @OA\Property(property="id_tinggal", type="integer", example=1),
     *                 @OA\Property(property="id_transport", type="integer", example=1),
     *                 @OA\Property(property="id_hobi", type="integer", example=1),
     *                 @OA\Property(property="id_minat", type="integer", example=1),
     *                 @OA\Property(property="no_rekening", type="string", example="18710510004211"),
     *                 @OA\Property(property="berat_badan", type="string", example="72"),
     *                 @OA\Property(property="tinggi_badan", type="string", example="173"),
     *                 @OA\Property(property="instansi_kerja", type="string", example="Universitas Lampung"),
     *                 @OA\Property(property="email_ortu", type="string", example="mujiyono@gmail.com"),
     *                 @OA\Property(property="show_hp", type="string", example="1"),
     *                 @OA\Property(property="show_kota", type="string", example="1"),
     *                 @OA\Property(property="show_hobi", type="string", example="1"),
     *                 @OA\Property(property="show_minat", type="string", example="1"),
     *             )
     *         )
     *     ),
     *     @OA\Response(
     *          response=200,
     *          description="Success Update Mahasiswa.",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(property="data", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="id", type="integer", example=1),
     *                      @OA\Property(property="nama", type="string", example="Aulia Ahmad Nabil"),
     *                      @OA\Property(property="gelar_depan", type="string", example="H."),
     *                      @OA\Property(property="gelar_belakang", type="string", example="S. Kom."),
     *                      @OA\Property(property="jenis_kelamin", type="string", example="L"),
     *                      @OA\Property(property="tempat_lahir", type="string", example="Bandar Lampung"),
     *                      @OA\Property(property="tgl_lahir", type="date", example="2000-05-10"),
     *                      @OA\Property(property="alamat", type="string", example="Perumahan Nusan"),
     *                      @OA\Property(property="telepon", type="string", example="0721"),
     *                      @OA\Property(property="hp", type="string", example="082222222222"),
     *                      @OA\Property(property="hp_2", type="string", example="08961234567"),
     *                      @OA\Property(property="email", type="string", example="nabilunited2@gmail.com"),
     *                      @OA\Property(property="gol_darah", type="string", example="O"),
     *                      @OA\Property(property="status_nikah", type="string", example="B"),
     *                      @OA\Property(property="nik", type="string", example="1871051005000099"),
     *                      @OA\Property(property="no_kk", type="string", example="18710510004211"),
     *                      @OA\Property(property="rt", type="string", example="02"),
     *                      @OA\Property(property="rw", type="string", example="02"),
     *                      @OA\Property(property="dusun", type="string", example="konoha"),
     *                      @OA\Property(property="desa", type="string", example="durian runtuh"),
     *                      @OA\Property(property="no_kps", type="string", example="281101010101"),
     *                      @OA\Property(property="id_agama", type="integer", example=1),
     *                      @OA\Property(property="id_negara", type="integer", example=1),
     *                      @OA\Property(property="id_kota", type="integer", example=1),
     *                      @OA\Property(property="id_kecamatan", type="integer", example=1),
     *                      @OA\Property(property="id_suku", type="integer", example=1),
     *                      @OA\Property(property="id_pekerjaan", type="integer", example=1),
     *                      @OA\Property(property="id_penghasilan", type="integer", example=1),
     *                      @OA\Property(property="id_tinggal", type="integer", example=1),
     *                      @OA\Property(property="id_transport", type="integer", example=1),
     *                      @OA\Property(property="id_hobi", type="integer", example=1),
     *                      @OA\Property(property="id_minat", type="integer", example=1),
     *                      @OA\Property(property="no_rekening", type="string", example="18710510004211"),
     *                      @OA\Property(property="berat_badan", type="string", example="72"),
     *                      @OA\Property(property="tinggi_badan", type="string", example="173"),
     *                      @OA\Property(property="instansi_kerja", type="string", example="Universitas Lampung"),
     *                      @OA\Property(property="email_ortu", type="string", example="mujiyono@gmail.com"),
     *                      @OA\Property(property="show_hp", type="string", example="1"),
     *                      @OA\Property(property="show_kota", type="string", example="1"),
     *                      @OA\Property(property="show_hobi", type="string", example="1"),
     *                      @OA\Property(property="show_minat", type="string", example="1"),
     *                      @OA\Property(property="is_valid_email", type="string", example="1"),
     *                      @OA\Property(property="id_file_akta_kelahiran", type="guid", example="2e7b8f7c-b8f7-4f0f-b8e2-c8f8f8f8f8f8"),
     *                  ),
     *              ),
     *              @OA\Property(property="debug", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="query", type="string", example="update ak_mahasiswa set ak_mahasiswa.id = 1 where ak_mahasiswa.id = 1"),
     *                      @OA\Property(property="time", type="integer", example=8.13),
     *                  ),
     *              ),
     *          ),
     *       ),
     *     @OA\Response(response=404, description="Error: Not Found",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(property="error", type="object",
     *                      @OA\Property(property="code", type="integer", example=404),
     *                      @OA\Property(property="message", type="string", example="Data tidak ditemukan"),
     *                      @OA\Property(property="debug", type="object",
     *                          @OA\Property(property="message", type="string", example="No query results for model [App\Models\Mahasiswa] 1"),
     *                          @OA\Property(property="files", type="object",
     *                              @OA\Property(type="string", example="/Users/brondol/Applications/siakadcloud/master/vendor/illuminate/database/Eloquent/Builder.php baris 434"),
     *                          ),
     *                      ),
     *              ),
     *              @OA\Property(property="debug", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="query", type="string", example="select * from ak_mahasiswa where ak_mahasiswa.id = 1 limit 1"),
     *                      @OA\Property(property="time", type="integer", example=2.25),
     *                  ),
     *              ),
     *          ),
     *     ),
     * )
     */

    /**
     * @OA\Delete(
     *     path="/v1/mahasiswa/{id}",
     *     summary="Delete mahasiswa",
     *     tags={"Mahasiswa"},
     *     security={{"bearerAuth": {}}},
     *     @OA\Parameter(
     *         description="id mahasiswa",
     *         in="path",
     *         name="id",
     *         required=true,
     *         @OA\Schema(type="integer"),
     *         @OA\Examples(example="int", value="1", summary="An int value."),
     *     ),
     *     @OA\Response(
     *          response=200,
     *          description="Berhasil Menghapus Mahasiswa"
     *       ),
     *     @OA\Response(response=404, description="Error: Not Found",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(property="error", type="object",
     *                      @OA\Property(property="code", type="integer", example=404),
     *                      @OA\Property(property="message", type="string", example="Data tidak ditemukan"),
     *                      @OA\Property(property="debug", type="object",
     *                          @OA\Property(property="message", type="string", example="No query results for model [App\Models\Mahasiswa] 1"),
     *                          @OA\Property(property="files", type="object",
     *                              @OA\Property(type="string", example="/Users/brondol/Applications/siakadcloud/master/vendor/illuminate/database/Eloquent/Builder.php baris 434"),
     *                          ),
     *                      ),
     *              ),
     *              @OA\Property(property="debug", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="query", type="string", example="select * from ak_mahasiswa where ak_mahasiswa.id = 1 limit 1"),
     *                      @OA\Property(property="time", type="integer", example=2.25),
     *                  ),
     *              ),
     *          ),
     *     ),
     * )
     */

    /**
     *     @OA\Schema(
     *         schema="Mahasiswa",
     *         @OA\Xml(name="Mahasiswa"),
     * required={"nama", "jenis_kelamin", "tempat_lahir", "tgl_lahir", "show_hp", "show_kota", "show_hobi", "show_minat", "is_valid_email"},
     *         @OA\Property(property="id", type="integer", example=1),
     *         @OA\Property(property="nama", type="string", example="Aulia Ahmad Nabil"),
     *         @OA\Property(property="gelar_depan", type="string", example="H."),
     *         @OA\Property(property="gelar_belakang", type="string", example="S. Kom."),
     *         @OA\Property(property="jenis_kelamin", type="string", example="L"),
     *         @OA\Property(property="tempat_lahir", type="string", example="Bandar Lampung"),
     *         @OA\Property(property="tgl_lahir", type="date", example="2000-05-10"),
     *         @OA\Property(property="alamat", type="string", example="Perumahan Nusantara"),
     *         @OA\Property(property="telepon", type="string", example="0721-1234567"),
     *         @OA\Property(property="hp", type="string", example="082222222222"),
     *         @OA\Property(property="hp_2", type="string", example="08961234567"),
     *         @OA\Property(property="email", type="string", example="nabilunited2@gmail.com"),
     *         @OA\Property(property="gol_darah", type="string", example="O"),
     *         @OA\Property(property="status_nikah", type="string", example="B"),
     *         @OA\Property(property="nik", type="string", example="1871051005000099"),
     *         @OA\Property(property="no_kk", type="string", example="18710510004211"),
     *         @OA\Property(property="rt", type="string", example="02"),
     *         @OA\Property(property="rw", type="string", example="02"),
     *         @OA\Property(property="dusun", type="string", example="konoha"),
     *         @OA\Property(property="desa", type="string", example="durian runtuh"),
     *         @OA\Property(property="no_kps", type="string", example="281101010101"),
     *         @OA\Property(property="id_agama", type="integer", example=1),
     *         @OA\Property(property="id_negara", type="integer", example=1),
     *         @OA\Property(property="id_kota", type="integer", example=1),
     *         @OA\Property(property="id_kecamatan", type="integer", example=1),
     *         @OA\Property(property="id_suku", type="integer", example=1),
     *         @OA\Property(property="id_pekerjaan", type="integer", example=1),
     *         @OA\Property(property="id_penghasilan", type="integer", example=1),
     *         @OA\Property(property="id_tinggal", type="integer", example=1),
     *         @OA\Property(property="id_transport", type="integer", example=1),
     *         @OA\Property(property="id_hobi", type="integer", example=1),
     *         @OA\Property(property="id_minat", type="integer", example=1),
     *         @OA\Property(property="no_rekening", type="string", example="18710510004211"),
     *         @OA\Property(property="berat_badan", type="string", example="72"),
     *         @OA\Property(property="tinggi_badan", type="string", example="173"),
     *         @OA\Property(property="instansi_kerja", type="string", example="Universitas Lampung"),
     *         @OA\Property(property="email_ortu", type="string", example="mujiyono@gmail.com"),
     *         @OA\Property(property="show_hp", type="string", example="1"),
     *         @OA\Property(property="show_kota", type="string", example="1"),
     *         @OA\Property(property="show_hobi", type="string", example="1"),
     *         @OA\Property(property="show_minat", type="string", example="1"),
     *         @OA\Property(property="is_valid_email", type="string", example="1"),
     *         @OA\Property(property="id_file_akta_kelahiran", type="guid", example="2e7b8f7c-b8f7-4f0f-b8e2-c8f8f8f8f8f8"),
     *     ),
     */
}
