<?php

namespace App\Http\Controllers\V1;

use Siakad\Controller;

class PegawaiController extends Controller
{
    /**
     *
     * @OA\Get(
     *      path="/v1/pegawai",
     *      tags={"Pegawai"},
     *      summary="List Pegawai",
     *      security={{"bearerAuth": {}}},
     *      @OA\Response(
     *          response=200,
     *          description="Get list of pegawai.",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(property="data", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="id", type="integer", example=""),
     *                      @OA\Property(property="nama", type="string", example=""),
     *                      @OA\Property(property="gelar_depan", type="string", example=""),
     *                      @OA\Property(property="gelar_belakang", type="string", example=""),
     *                      @OA\Property(property="jenis_kelamin", type="string", example=""),
     *                      @OA\Property(property="tgl_lahir", type="date", example=""),
     *                      @OA\Property(property="tempat_lahir", type="string", example=""),
     *                      @OA\Property(property="alamat", type="string", example=""),
     *                      @OA\Property(property="telepon", type="string", example=""),
     *                      @OA\Property(property="email", type="string", example=""),
     *                      @OA\Property(property="id_agama", type="integer", example=""),
     *                      @OA\Property(property="id_universitas", type="integer", example=""),
     *                      @OA\Property(property="id_kota", type="integer", example=""),
     *                      @OA\Property(property="id_hobi", type="integer", example=""),
     *                      @OA\Property(property="id_minat", type="integer", example=""),
     *                      @OA\Property(property="show_hp", type="string", example=""),
     *                      @OA\Property(property="show_email", type="string", example=""),
     *                      @OA\Property(property="show_kota", type="string", example=""),
     *                      @OA\Property(property="show_hobi", type="string", example=""),
     *                      @OA\Property(property="show_minat", type="string", example=""),
     *                      @OA\Property(property="is_valid_email", type="string", example=""),
     *                      @OA\Property(property="id_file_ttd", type="guid", example=""),
     *                  ),
     *              ),
     *              @OA\Property(property="info", type="object",
     *                      @OA\Property(property="total", type="integer", example=10),
     *                      @OA\Property(property="page", type="integer", example=1),
     *                      @OA\Property(property="last_page", type="integer", example=1),
     *                      @OA\Property(property="count", type="integer", example=10),
     *                      @OA\Property(property="start", type="integer", example=1),
     *                      @OA\Property(property="end", type="integer", example=10),
     *              ),
     *              @OA\Property(property="debug", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="query", type="string", example="select count(*) as aggregate from ak_pegawai"),
     *                      @OA\Property(property="time", type="integer", example=59.0),
     *                  ),
     *              ),
     *          ),
     *       ),
     * )
     */

    /**
     * @OA\Get(
     *     path="/v1/pegawai/{id}",
     *     summary="Data Pegawai",
     *     tags={"Pegawai"},
     *     security={{"bearerAuth": {}}},
     *     @OA\Parameter(
     *         description="id pegawai",
     *         in="path",
     *         name="id",
     *         required=true,
     *         @OA\Schema(type="integer"),
     *         @OA\Examples(example="int", value="1", summary="An int value."),
     *     ),
     *     @OA\Response(
     *          response=200,
     *          description="Get data of pegawai.",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(property="data", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="id", type="integer", example=""),
     *                      @OA\Property(property="nama", type="string", example=""),
     *                      @OA\Property(property="gelar_depan", type="string", example=""),
     *                      @OA\Property(property="gelar_belakang", type="string", example=""),
     *                      @OA\Property(property="jenis_kelamin", type="string", example=""),
     *                      @OA\Property(property="tgl_lahir", type="date", example=""),
     *                      @OA\Property(property="tempat_lahir", type="string", example=""),
     *                      @OA\Property(property="alamat", type="string", example=""),
     *                      @OA\Property(property="telepon", type="string", example=""),
     *                      @OA\Property(property="email", type="string", example=""),
     *                      @OA\Property(property="id_agama", type="integer", example=""),
     *                      @OA\Property(property="id_universitas", type="integer", example=""),
     *                      @OA\Property(property="id_kota", type="integer", example=""),
     *                      @OA\Property(property="id_hobi", type="integer", example=""),
     *                      @OA\Property(property="id_minat", type="integer", example=""),
     *                      @OA\Property(property="show_hp", type="string", example=""),
     *                      @OA\Property(property="show_email", type="string", example=""),
     *                      @OA\Property(property="show_kota", type="string", example=""),
     *                      @OA\Property(property="show_hobi", type="string", example=""),
     *                      @OA\Property(property="show_minat", type="string", example=""),
     *                      @OA\Property(property="is_valid_email", type="string", example=""),
     *                      @OA\Property(property="id_file_ttd", type="guid", example=""),
     *                  ),
     *              ),
     *              @OA\Property(property="debug", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="query", type="string", example="SELECT * FROM ak_pegawai WHERE ak_pegawai.id = 1 limit 1"),
     *                      @OA\Property(property="time", type="integer", example=59.0),
     *                  ),
     *              ),
     *          ),
     *     ),
     *     @OA\Response(response=404, description="Error: Not Found",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(property="error", type="object",
     *                      @OA\Property(property="code", type="integer", example=404),
     *                      @OA\Property(property="message", type="string", example="Data tidak ditemukan"),
     *                      @OA\Property(property="debug", type="object",
     *                          @OA\Property(property="message", type="string", example="No query results for model [App\Models\Pegawai] 1"),
     *                          @OA\Property(property="files", type="object",
     *                              @OA\Property(type="string", example="/Users/brondol/Applications/siakadcloud/master/vendor/illuminate/database/Eloquent/Builder.php baris 434"),
     *                          ),
     *                      ),
     *              ),
     *              @OA\Property(property="debug", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="query", type="string", example="select * from ak_mahasiswa where ak_mahasiswa.id = 1 limit 1"),
     *                      @OA\Property(property="time", type="integer", example=2.25),
     *                  ),
     *              ),
     *          ),
     *     ),
     * )
     */

    /**
     * @OA\Post(
     *     path="/v1/pegawai",
     *     summary="Add Pegawai",
     *     tags={"Pegawai"},
     *     security={{"bearerAuth": {}}},
     *     @OA\RequestBody(
     *         @OA\MediaType(
     *             mediaType="application/json",
     *             @OA\Schema(
     *                 @OA\Property(property="nama", type="string", example=""),
     *                 @OA\Property(property="gelar_depan", type="string", example=""),
     *                 @OA\Property(property="gelar_belakang", type="string", example=""),
     *                 @OA\Property(property="jenis_kelamin", type="string", example=""),
     *                 @OA\Property(property="tgl_lahir", type="date", example=""),
     *                 @OA\Property(property="tempat_lahir", type="string", example=""),
     *                 @OA\Property(property="alamat", type="string", example=""),
     *                 @OA\Property(property="telepon", type="string", example=""),
     *                 @OA\Property(property="email", type="string", example=""),
     *                 @OA\Property(property="id_agama", type="integer", example=""),
     *                 @OA\Property(property="id_universitas", type="integer", example=""),
     *                 @OA\Property(property="id_kota", type="integer", example=""),
     *                 @OA\Property(property="id_hobi", type="integer", example=""),
     *                 @OA\Property(property="id_minat", type="integer", example=""),
     *                 @OA\Property(property="show_hp", type="string", example=""),
     *                 @OA\Property(property="show_email", type="string", example=""),
     *                 @OA\Property(property="show_kota", type="string", example=""),
     *                 @OA\Property(property="show_hobi", type="string", example=""),
     *                 @OA\Property(property="show_minat", type="string", example=""),
     *                 @OA\Property(property="is_valid_email", type="string", example=""),
     *                 @OA\Property(property="id_file_ttd", type="guid", example=""),
     *             )
     *         )
     *     ),
     *     @OA\Response(
     *          response=201,
     *          description="Success add new pegawai.",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(property="data", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="id", type="integer", example=""),
     *                      @OA\Property(property="nama", type="string", example=""),
     *                      @OA\Property(property="gelar_depan", type="string", example=""),
     *                      @OA\Property(property="gelar_belakang", type="string", example=""),
     *                      @OA\Property(property="jenis_kelamin", type="string", example=""),
     *                      @OA\Property(property="tgl_lahir", type="date", example=""),
     *                      @OA\Property(property="tempat_lahir", type="string", example=""),
     *                      @OA\Property(property="alamat", type="string", example=""),
     *                      @OA\Property(property="telepon", type="string", example=""),
     *                      @OA\Property(property="email", type="string", example=""),
     *                      @OA\Property(property="id_agama", type="integer", example=""),
     *                      @OA\Property(property="id_universitas", type="integer", example=""),
     *                      @OA\Property(property="id_kota", type="integer", example=""),
     *                      @OA\Property(property="id_hobi", type="integer", example=""),
     *                      @OA\Property(property="id_minat", type="integer", example=""),
     *                      @OA\Property(property="show_hp", type="string", example=""),
     *                      @OA\Property(property="show_email", type="string", example=""),
     *                      @OA\Property(property="show_kota", type="string", example=""),
     *                      @OA\Property(property="show_hobi", type="string", example=""),
     *                      @OA\Property(property="show_minat", type="string", example=""),
     *                      @OA\Property(property="is_valid_email", type="string", example=""),
     *                      @OA\Property(property="id_file_ttd", type="guid", example=""),
     *                  ),
     *              ),
     *              @OA\Property(property="debug", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="query", type="string", example="insert into ak_pegawai () values () returning id"),
     *                      @OA\Property(property="time", type="integer", example=8.13),
     *                  ),
     *              ),
     *          ),
     *     ),
     *     @OA\Response(response=400, description="Bad Request",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(property="error", type="object",
     *                      @OA\Property(property="code", type="integer", example=400),
     *                      @OA\Property(property="message", type="string", example="Data yang dikirimkan tidak valid"),
     *                      @OA\Property(property="validation", type="object",
     *                          @OA\Property(property="nama_field", type="array",
     *                              @OA\Items(type="string", example="Harus diisi"),
     *                          ),
     *                      ),
     *              ),
     *          ),
     *     ),
     * )
     */

    /**
     * @OA\Put(
     *     path="/v1/pegawai/{id}",
     *     summary="Update pegawai",
     *     tags={"Pegawai"},
     *     security={{"bearerAuth": {}}},
     *     @OA\Parameter(
     *         description="id pegawai",
     *         in="path",
     *         name="id",
     *         required=true,
     *         @OA\Schema(type="integer"),
     *         @OA\Examples(example="int", value="1", summary="An int value."),
     *     ),
     *     @OA\RequestBody(
     *         @OA\MediaType(
     *             mediaType="application/json",
     *             @OA\Schema(
     *                 @OA\Property(property="nama", type="string", example=""),
     *                 @OA\Property(property="gelar_depan", type="string", example=""),
     *                 @OA\Property(property="gelar_belakang", type="string", example=""),
     *                 @OA\Property(property="jenis_kelamin", type="string", example=""),
     *                 @OA\Property(property="tgl_lahir", type="date", example=""),
     *                 @OA\Property(property="tempat_lahir", type="string", example=""),
     *                 @OA\Property(property="alamat", type="string", example=""),
     *                 @OA\Property(property="telepon", type="string", example=""),
     *                 @OA\Property(property="email", type="string", example=""),
     *                 @OA\Property(property="id_agama", type="integer", example=""),
     *                 @OA\Property(property="id_universitas", type="integer", example=""),
     *                 @OA\Property(property="id_kota", type="integer", example=""),
     *                 @OA\Property(property="id_hobi", type="integer", example=""),
     *                 @OA\Property(property="id_minat", type="integer", example=""),
     *                 @OA\Property(property="show_hp", type="string", example=""),
     *                 @OA\Property(property="show_email", type="string", example=""),
     *                 @OA\Property(property="show_kota", type="string", example=""),
     *                 @OA\Property(property="show_hobi", type="string", example=""),
     *                 @OA\Property(property="show_minat", type="string", example=""),
     *                 @OA\Property(property="is_valid_email", type="string", example=""),
     *                 @OA\Property(property="id_file_ttd", type="guid", example=""),
     *             )
     *         )
     *     ),
     *     @OA\Response(
     *          response=200,
     *          description="Success Update Pegawai.",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(property="data", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="id", type="integer", example=""),
     *                      @OA\Property(property="nama", type="string", example=""),
     *                      @OA\Property(property="gelar_depan", type="string", example=""),
     *                      @OA\Property(property="gelar_belakang", type="string", example=""),
     *                      @OA\Property(property="jenis_kelamin", type="string", example=""),
     *                      @OA\Property(property="tgl_lahir", type="date", example=""),
     *                      @OA\Property(property="tempat_lahir", type="string", example=""),
     *                      @OA\Property(property="alamat", type="string", example=""),
     *                      @OA\Property(property="telepon", type="string", example=""),
     *                      @OA\Property(property="email", type="string", example=""),
     *                      @OA\Property(property="id_agama", type="integer", example=""),
     *                      @OA\Property(property="id_universitas", type="integer", example=""),
     *                      @OA\Property(property="id_kota", type="integer", example=""),
     *                      @OA\Property(property="id_hobi", type="integer", example=""),
     *                      @OA\Property(property="id_minat", type="integer", example=""),
     *                      @OA\Property(property="show_hp", type="string", example=""),
     *                      @OA\Property(property="show_email", type="string", example=""),
     *                      @OA\Property(property="show_kota", type="string", example=""),
     *                      @OA\Property(property="show_hobi", type="string", example=""),
     *                      @OA\Property(property="show_minat", type="string", example=""),
     *                      @OA\Property(property="is_valid_email", type="string", example=""),
     *                      @OA\Property(property="id_file_ttd", type="guid", example=""),
     *                  ),
     *              ),
     *              @OA\Property(property="debug", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="query", type="string", example="update ak_pegawai set ak_pegawai.id = 1 where ak_pegawai.id = 1"),
     *                      @OA\Property(property="time", type="integer", example=8.13),
     *                  ),
     *              ),
     *          ),
     *       ),
     *     @OA\Response(response=404, description="Error: Not Found",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(property="error", type="object",
     *                      @OA\Property(property="code", type="integer", example=404),
     *                      @OA\Property(property="message", type="string", example="Data tidak ditemukan"),
     *                      @OA\Property(property="debug", type="object",
     *                          @OA\Property(property="message", type="string", example="No query results for model [App\Models\Pegawai] 1"),
     *                          @OA\Property(property="files", type="object",
     *                              @OA\Property(type="string", example="/Users/brondol/Applications/siakadcloud/master/vendor/illuminate/database/Eloquent/Builder.php baris 434"),
     *                          ),
     *                      ),
     *              ),
     *              @OA\Property(property="debug", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="query", type="string", example="select * from ak_mahasiswa where ak_mahasiswa.id = 1 limit 1"),
     *                      @OA\Property(property="time", type="integer", example=2.25),
     *                  ),
     *              ),
     *          ),
     *     ),
     * )
     */

    /**
     * @OA\Delete(
     *     path="/v1/pegawai/{id}",
     *     summary="Delete pegawai",
     *     tags={"Pegawai"},
     *     security={{"bearerAuth": {}}},
     *     @OA\Parameter(
     *         description="id pegawai",
     *         in="path",
     *         name="id",
     *         required=true,
     *         @OA\Schema(type="integer"),
     *         @OA\Examples(example="int", value="1", summary="An int value."),
     *     ),
     *     @OA\Response(
     *          response=200,
     *          description="Berhasil Menghapus Pegawai"
     *       ),
     *     @OA\Response(response=404, description="Error: Not Found",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(property="error", type="object",
     *                      @OA\Property(property="code", type="integer", example=404),
     *                      @OA\Property(property="message", type="string", example="Data tidak ditemukan"),
     *                      @OA\Property(property="debug", type="object",
     *                          @OA\Property(property="message", type="string", example="No query results for model [App\Models\Pegawai] 1"),
     *                          @OA\Property(property="files", type="object",
     *                              @OA\Property(type="string", example="/Users/brondol/Applications/siakadcloud/master/vendor/illuminate/database/Eloquent/Builder.php baris 434"),
     *                          ),
     *                      ),
     *              ),
     *              @OA\Property(property="debug", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="query", type="string", example="select * from ak_mahasiswa where ak_mahasiswa.id = 1 limit 1"),
     *                      @OA\Property(property="time", type="integer", example=2.25),
     *                  ),
     *              ),
     *          ),
     *     ),
     * )
     */

    /**
     *     @OA\Schema(
     *         schema="Pegawai",
     *         @OA\Xml(name="Pegawai"),
     *         @OA\Property(property="id", type="integer", example=""),
     *         @OA\Property(property="nama", type="string", example=""),
     *         @OA\Property(property="gelar_depan", type="string", example=""),
     *         @OA\Property(property="gelar_belakang", type="string", example=""),
     *         @OA\Property(property="jenis_kelamin", type="string", example=""),
     *         @OA\Property(property="tgl_lahir", type="date", example=""),
     *         @OA\Property(property="tempat_lahir", type="string", example=""),
     *         @OA\Property(property="alamat", type="string", example=""),
     *         @OA\Property(property="telepon", type="string", example=""),
     *         @OA\Property(property="email", type="string", example=""),
     *         @OA\Property(property="id_agama", type="integer", example=""),
     *         @OA\Property(property="id_universitas", type="integer", example=""),
     *         @OA\Property(property="id_kota", type="integer", example=""),
     *         @OA\Property(property="id_hobi", type="integer", example=""),
     *         @OA\Property(property="id_minat", type="integer", example=""),
     *         @OA\Property(property="show_hp", type="string", example=""),
     *         @OA\Property(property="show_email", type="string", example=""),
     *         @OA\Property(property="show_kota", type="string", example=""),
     *         @OA\Property(property="show_hobi", type="string", example=""),
     *         @OA\Property(property="show_minat", type="string", example=""),
     *         @OA\Property(property="is_valid_email", type="string", example=""),
     *         @OA\Property(property="id_file_ttd", type="guid", example=""),
     *     ),
     */
}
        