<?php

namespace App\Http\Controllers\V1;

use Siakad\Controller;

class PeriodeController extends Controller
{
    /**
     *
     * @OA\Get(
     *      path="/v1/periode",
     *      tags={"Periode"},
     *      summary="List Periode",
     *      security={{"bearerAuth": {}}},
     *      @OA\Response(
     *          response=200,
     *          description="Get list of periode.",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(property="data", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="id", type="integer", example=""),
     *                      @OA\Property(property="id_pt", type="integer", example=""),
     *                      @OA\Property(property="kode_periode", type="string", example=""),
     *                      @OA\Property(property="nama_periode", type="string", example=""),
     *                      @OA\Property(property="nama_singkat", type="string", example=""),
     *                      @OA\Property(property="id_tahun_ajaran", type="integer", example=""),
     *                      @OA\Property(property="tgl_awal", type="date", example=""),
     *                      @OA\Property(property="tgl_akhir", type="date", example=""),
     *                      @OA\Property(property="tgl_awal_uts", type="date", example=""),
     *                      @OA\Property(property="tgl_akhir_uts", type="date", example=""),
     *                      @OA\Property(property="tgl_awal_uas", type="date", example=""),
     *                      @OA\Property(property="tgl_akhir_uas", type="date", example=""),
     *                      @OA\Property(property="bulan_awal_tagihan", type="string", example=""),
     *                      @OA\Property(property="bulan_akhir_tagihan", type="string", example=""),
     *                      @OA\Property(property="pertemuan_kuliah", type="integer", example="16"),
     *                      @OA\Property(property="minimal_absensi", type="decimal", example="80"),
     *                      @OA\Property(property="is_aktif", type="string", example=""),
     *                      @OA\Property(property="id_ketua_ujian", type="integer", example=""),
     *                  ),
     *              ),
     *              @OA\Property(property="info", type="object",
     *                      @OA\Property(property="total", type="integer", example=10),
     *                      @OA\Property(property="page", type="integer", example=1),
     *                      @OA\Property(property="last_page", type="integer", example=1),
     *                      @OA\Property(property="count", type="integer", example=10),
     *                      @OA\Property(property="start", type="integer", example=1),
     *                      @OA\Property(property="end", type="integer", example=10),
     *              ),
     *              @OA\Property(property="debug", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="query", type="string", example="select count(*) as aggregate from ms_periode"),
     *                      @OA\Property(property="time", type="integer", example=59.0),
     *                  ),
     *              ),
     *          ),
     *       ),
     * )
     */

    /**
     * @OA\Get(
     *     path="/v1/periode/{id}",
     *     summary="Data Periode",
     *     tags={"Periode"},
     *     security={{"bearerAuth": {}}},
     *     @OA\Parameter(
     *         description="id periode",
     *         in="path",
     *         name="id",
     *         required=true,
     *         @OA\Schema(type="integer"),
     *         @OA\Examples(example="int", value="1", summary="An int value."),
     *     ),
     *     @OA\Response(
     *          response=200,
     *          description="Get data of periode.",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(property="data", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="id", type="integer", example=""),
     *                      @OA\Property(property="id_pt", type="integer", example=""),
     *                      @OA\Property(property="kode_periode", type="string", example=""),
     *                      @OA\Property(property="nama_periode", type="string", example=""),
     *                      @OA\Property(property="nama_singkat", type="string", example=""),
     *                      @OA\Property(property="id_tahun_ajaran", type="integer", example=""),
     *                      @OA\Property(property="tgl_awal", type="date", example=""),
     *                      @OA\Property(property="tgl_akhir", type="date", example=""),
     *                      @OA\Property(property="tgl_awal_uts", type="date", example=""),
     *                      @OA\Property(property="tgl_akhir_uts", type="date", example=""),
     *                      @OA\Property(property="tgl_awal_uas", type="date", example=""),
     *                      @OA\Property(property="tgl_akhir_uas", type="date", example=""),
     *                      @OA\Property(property="bulan_awal_tagihan", type="string", example=""),
     *                      @OA\Property(property="bulan_akhir_tagihan", type="string", example=""),
     *                      @OA\Property(property="pertemuan_kuliah", type="integer", example="16"),
     *                      @OA\Property(property="minimal_absensi", type="decimal", example="80"),
     *                      @OA\Property(property="is_aktif", type="string", example=""),
     *                      @OA\Property(property="id_ketua_ujian", type="integer", example=""),
     *                  ),
     *              ),
     *              @OA\Property(property="debug", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="query", type="string", example="SELECT * FROM ms_periode WHERE ms_periode.id = 1 limit 1"),
     *                      @OA\Property(property="time", type="integer", example=59.0),
     *                  ),
     *              ),
     *          ),
     *     ),
     *     @OA\Response(response=404, description="Error: Not Found",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(property="error", type="object",
     *                      @OA\Property(property="code", type="integer", example=404),
     *                      @OA\Property(property="message", type="string", example="Data tidak ditemukan"),
     *                      @OA\Property(property="debug", type="object",
     *                          @OA\Property(property="message", type="string", example="No query results for model [App\Models\Periode] 1"),
     *                          @OA\Property(property="files", type="object",
     *                              @OA\Property(type="string", example="/Users/brondol/Applications/siakadcloud/master/vendor/illuminate/database/Eloquent/Builder.php baris 434"),
     *                          ),
     *                      ),
     *              ),
     *              @OA\Property(property="debug", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="query", type="string", example="select * from ak_mahasiswa where ak_mahasiswa.id = 1 limit 1"),
     *                      @OA\Property(property="time", type="integer", example=2.25),
     *                  ),
     *              ),
     *          ),
     *     ),
     * )
     */

    /**
     * @OA\Post(
     *     path="/v1/periode",
     *     summary="Add Periode",
     *     tags={"Periode"},
     *     security={{"bearerAuth": {}}},
     *     @OA\RequestBody(
     *         @OA\MediaType(
     *             mediaType="application/json",
     *             @OA\Schema(
     *                 @OA\Property(property="kode_periode", type="string", example=""),
     *                 @OA\Property(property="nama_periode", type="string", example=""),
     *                 @OA\Property(property="nama_singkat", type="string", example=""),
     *                 @OA\Property(property="id_tahun_ajaran", type="integer", example=""),
     *                 @OA\Property(property="tgl_awal", type="date", example=""),
     *                 @OA\Property(property="tgl_akhir", type="date", example=""),
     *                 @OA\Property(property="tgl_awal_uts", type="date", example=""),
     *                 @OA\Property(property="tgl_akhir_uts", type="date", example=""),
     *                 @OA\Property(property="tgl_awal_uas", type="date", example=""),
     *                 @OA\Property(property="tgl_akhir_uas", type="date", example=""),
     *                 @OA\Property(property="bulan_awal_tagihan", type="string", example=""),
     *                 @OA\Property(property="bulan_akhir_tagihan", type="string", example=""),
     *                 @OA\Property(property="pertemuan_kuliah", type="integer", example="16"),
     *                 @OA\Property(property="minimal_absensi", type="decimal", example="80"),
     *                 @OA\Property(property="is_aktif", type="string", example=""),
     *                 @OA\Property(property="id_ketua_ujian", type="integer", example=""),
     *             )
     *         )
     *     ),
     *     @OA\Response(
     *          response=201,
     *          description="Success add new periode.",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(property="data", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="id", type="integer", example=""),
     *                      @OA\Property(property="id_pt", type="integer", example=""),
     *                      @OA\Property(property="kode_periode", type="string", example=""),
     *                      @OA\Property(property="nama_periode", type="string", example=""),
     *                      @OA\Property(property="nama_singkat", type="string", example=""),
     *                      @OA\Property(property="id_tahun_ajaran", type="integer", example=""),
     *                      @OA\Property(property="tgl_awal", type="date", example=""),
     *                      @OA\Property(property="tgl_akhir", type="date", example=""),
     *                      @OA\Property(property="tgl_awal_uts", type="date", example=""),
     *                      @OA\Property(property="tgl_akhir_uts", type="date", example=""),
     *                      @OA\Property(property="tgl_awal_uas", type="date", example=""),
     *                      @OA\Property(property="tgl_akhir_uas", type="date", example=""),
     *                      @OA\Property(property="bulan_awal_tagihan", type="string", example=""),
     *                      @OA\Property(property="bulan_akhir_tagihan", type="string", example=""),
     *                      @OA\Property(property="pertemuan_kuliah", type="integer", example="16"),
     *                      @OA\Property(property="minimal_absensi", type="decimal", example="80"),
     *                      @OA\Property(property="is_aktif", type="string", example=""),
     *                      @OA\Property(property="id_ketua_ujian", type="integer", example=""),
     *                  ),
     *              ),
     *              @OA\Property(property="debug", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="query", type="string", example="insert into ms_periode () values () returning id"),
     *                      @OA\Property(property="time", type="integer", example=8.13),
     *                  ),
     *              ),
     *          ),
     *     ),
     *     @OA\Response(response=400, description="Bad Request",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(property="error", type="object",
     *                      @OA\Property(property="code", type="integer", example=400),
     *                      @OA\Property(property="message", type="string", example="Data yang dikirimkan tidak valid"),
     *                      @OA\Property(property="validation", type="object",
     *                          @OA\Property(property="nama_field", type="array",
     *                              @OA\Items(type="string", example="Harus diisi"),
     *                          ),
     *                      ),
     *              ),
     *          ),
     *     ),
     * )
     */

    /**
     * @OA\Put(
     *     path="/v1/periode/{id}",
     *     summary="Update periode",
     *     tags={"Periode"},
     *     security={{"bearerAuth": {}}},
     *     @OA\Parameter(
     *         description="id periode",
     *         in="path",
     *         name="id",
     *         required=true,
     *         @OA\Schema(type="integer"),
     *         @OA\Examples(example="int", value="1", summary="An int value."),
     *     ),
     *     @OA\RequestBody(
     *         @OA\MediaType(
     *             mediaType="application/json",
     *             @OA\Schema(
     *                 @OA\Property(property="kode_periode", type="string", example=""),
     *                 @OA\Property(property="nama_periode", type="string", example=""),
     *                 @OA\Property(property="nama_singkat", type="string", example=""),
     *                 @OA\Property(property="id_tahun_ajaran", type="integer", example=""),
     *                 @OA\Property(property="tgl_awal", type="date", example=""),
     *                 @OA\Property(property="tgl_akhir", type="date", example=""),
     *                 @OA\Property(property="tgl_awal_uts", type="date", example=""),
     *                 @OA\Property(property="tgl_akhir_uts", type="date", example=""),
     *                 @OA\Property(property="tgl_awal_uas", type="date", example=""),
     *                 @OA\Property(property="tgl_akhir_uas", type="date", example=""),
     *                 @OA\Property(property="bulan_awal_tagihan", type="string", example=""),
     *                 @OA\Property(property="bulan_akhir_tagihan", type="string", example=""),
     *                 @OA\Property(property="pertemuan_kuliah", type="integer", example="16"),
     *                 @OA\Property(property="minimal_absensi", type="decimal", example="80"),
     *                 @OA\Property(property="is_aktif", type="string", example=""),
     *                 @OA\Property(property="id_ketua_ujian", type="integer", example=""),
     *             )
     *         )
     *     ),
     *     @OA\Response(
     *          response=200,
     *          description="Success Update Periode.",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(property="data", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="id", type="integer", example=""),
     *                      @OA\Property(property="id_pt", type="integer", example=""),
     *                      @OA\Property(property="kode_periode", type="string", example=""),
     *                      @OA\Property(property="nama_periode", type="string", example=""),
     *                      @OA\Property(property="nama_singkat", type="string", example=""),
     *                      @OA\Property(property="id_tahun_ajaran", type="integer", example=""),
     *                      @OA\Property(property="tgl_awal", type="date", example=""),
     *                      @OA\Property(property="tgl_akhir", type="date", example=""),
     *                      @OA\Property(property="tgl_awal_uts", type="date", example=""),
     *                      @OA\Property(property="tgl_akhir_uts", type="date", example=""),
     *                      @OA\Property(property="tgl_awal_uas", type="date", example=""),
     *                      @OA\Property(property="tgl_akhir_uas", type="date", example=""),
     *                      @OA\Property(property="bulan_awal_tagihan", type="string", example=""),
     *                      @OA\Property(property="bulan_akhir_tagihan", type="string", example=""),
     *                      @OA\Property(property="pertemuan_kuliah", type="integer", example="16"),
     *                      @OA\Property(property="minimal_absensi", type="decimal", example="80"),
     *                      @OA\Property(property="is_aktif", type="string", example=""),
     *                      @OA\Property(property="id_ketua_ujian", type="integer", example=""),
     *                  ),
     *              ),
     *              @OA\Property(property="debug", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="query", type="string", example="update ms_periode set ms_periode.id = 1 where ms_periode.id = 1"),
     *                      @OA\Property(property="time", type="integer", example=8.13),
     *                  ),
     *              ),
     *          ),
     *       ),
     *     @OA\Response(response=404, description="Error: Not Found",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(property="error", type="object",
     *                      @OA\Property(property="code", type="integer", example=404),
     *                      @OA\Property(property="message", type="string", example="Data tidak ditemukan"),
     *                      @OA\Property(property="debug", type="object",
     *                          @OA\Property(property="message", type="string", example="No query results for model [App\Models\Periode] 1"),
     *                          @OA\Property(property="files", type="object",
     *                              @OA\Property(type="string", example="/Users/brondol/Applications/siakadcloud/master/vendor/illuminate/database/Eloquent/Builder.php baris 434"),
     *                          ),
     *                      ),
     *              ),
     *              @OA\Property(property="debug", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="query", type="string", example="select * from ak_mahasiswa where ak_mahasiswa.id = 1 limit 1"),
     *                      @OA\Property(property="time", type="integer", example=2.25),
     *                  ),
     *              ),
     *          ),
     *     ),
     * )
     */

    /**
     * @OA\Delete(
     *     path="/v1/periode/{id}",
     *     summary="Delete periode",
     *     tags={"Periode"},
     *     security={{"bearerAuth": {}}},
     *     @OA\Parameter(
     *         description="id periode",
     *         in="path",
     *         name="id",
     *         required=true,
     *         @OA\Schema(type="integer"),
     *         @OA\Examples(example="int", value="1", summary="An int value."),
     *     ),
     *     @OA\Response(
     *          response=200,
     *          description="Berhasil Menghapus Periode"
     *       ),
     *     @OA\Response(response=404, description="Error: Not Found",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(property="error", type="object",
     *                      @OA\Property(property="code", type="integer", example=404),
     *                      @OA\Property(property="message", type="string", example="Data tidak ditemukan"),
     *                      @OA\Property(property="debug", type="object",
     *                          @OA\Property(property="message", type="string", example="No query results for model [App\Models\Periode] 1"),
     *                          @OA\Property(property="files", type="object",
     *                              @OA\Property(type="string", example="/Users/brondol/Applications/siakadcloud/master/vendor/illuminate/database/Eloquent/Builder.php baris 434"),
     *                          ),
     *                      ),
     *              ),
     *              @OA\Property(property="debug", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="query", type="string", example="select * from ak_mahasiswa where ak_mahasiswa.id = 1 limit 1"),
     *                      @OA\Property(property="time", type="integer", example=2.25),
     *                  ),
     *              ),
     *          ),
     *     ),
     * )
     */

    /**
     *     @OA\Schema(
     *         schema="Periode",
     *         @OA\Xml(name="Periode"),
     *         @OA\Property(property="id", type="integer", example=""),
     *         @OA\Property(property="id_pt", type="integer", example=""),
     *         @OA\Property(property="kode_periode", type="string", example=""),
     *         @OA\Property(property="nama_periode", type="string", example=""),
     *         @OA\Property(property="nama_singkat", type="string", example=""),
     *         @OA\Property(property="id_tahun_ajaran", type="integer", example=""),
     *         @OA\Property(property="tgl_awal", type="date", example=""),
     *         @OA\Property(property="tgl_akhir", type="date", example=""),
     *         @OA\Property(property="tgl_awal_uts", type="date", example=""),
     *         @OA\Property(property="tgl_akhir_uts", type="date", example=""),
     *         @OA\Property(property="tgl_awal_uas", type="date", example=""),
     *         @OA\Property(property="tgl_akhir_uas", type="date", example=""),
     *         @OA\Property(property="bulan_awal_tagihan", type="string", example=""),
     *         @OA\Property(property="bulan_akhir_tagihan", type="string", example=""),
     *         @OA\Property(property="pertemuan_kuliah", type="integer", example="16"),
     *         @OA\Property(property="minimal_absensi", type="decimal", example="80"),
     *         @OA\Property(property="is_aktif", type="string", example=""),
     *         @OA\Property(property="id_ketua_ujian", type="integer", example=""),
     *     ),
     */
}
        