<?php

namespace App\Http\Controllers\V1;

use Siakad\Controller;
use Siakad\Response;

class UnitController extends Controller
{
    /**
     * Refresh cache
     */
    public function goCache()
    {
        return Response::show($this->service->cache());
    }
    /**
     *
     * @OA\Get(
     *      path="/v1/unit",
     *      tags={"Unit"},
     *      summary="List Unit",
     *      security={{"bearerAuth": {}}},
     *      @OA\Response(
     *          response=200,
     *          description="Get list of unit.",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(property="data", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="id", type="integer", example=1),
     *                      @OA\Property(property="id_pt", type="integer", example=1),
     *                      @OA\Property(property="nama_unit", type="string", example="Teknik Elektro"),
     *                      @OA\Property(property="nama_unit_en", type="string", example="Electrical Engineering"),
     *                      @OA\Property(property="nama_singkat", type="string", example="Teknik Elektro"),
     *                      @OA\Property(property="id_parent", type="integer", example=1),
     *                      @OA\Property(property="id_jenjang", type="integer", example=1),
     *                      @OA\Property(property="jenis_unit", type="string", example="P"),
     *                      @OA\Property(property="alamat", type="string", example="Jl. Sima"),
     *                      @OA\Property(property="telepon", type="string", example="08"),
     *                      @OA\Property(property="email", type="string", example="elektro@unila.ac.id"),
     *                      @OA\Property(property="website", type="string", example="elektro.unila.ac.id"),
     *                      @OA\Property(property="gelar", type="string", example="S.T."),
     *                      @OA\Property(property="gelar_en", type="string", example="S.T."),
     *                      @OA\Property(property="deskripsi_gelar", type="string", example="Sarjana Teknik (elektro)"),
     *                      @OA\Property(property="deskripsi_gelar_en", type="string", example="Bachelor of Engineering (Electrical)"),
     *                      @OA\Property(property="akreditasi", type="string", example="A"),
     *                      @OA\Property(property="sk_akreditasi", type="string", example="UIDA-SK-A-01/UNILA/2019"),
     *                      @OA\Property(property="tgl_akreditasi", type="date", example="2021-01-01"),
     *                      @OA\Property(property="tgl_sk_pendirian", type="date", example="2019-01-01"),
     *                      @OA\Property(property="id_periode_berdiri", type="integer", example=1),
     *                      @OA\Property(property="sks_lulus_min", type="integer", example=144),
     *                      @OA\Property(property="ipk_lulus_min", type="decimal", example=2.75),
     *                      @OA\Property(property="batas_sks_awal", type="integer", example=18),
     *                      @OA\Property(property="jumlah_pembimbing", type="integer", example=30),
     *                      @OA\Property(property="jumlah_penguji", type="integer", example=25),
     *                      @OA\Property(property="id_jenis_ta", type="string", example=1),
     *                      @OA\Property(property="kode_nim", type="string", example="021"),
     *                      @OA\Property(property="foto", type="string", example="http"),
     *                      @OA\Property(property="keterangan", type="string", example="Teknik elektro"),
     *                      @OA\Property(property="visi", type="string", example="elektro jaya"),
     *                      @OA\Property(property="misi", type="string", example="jaya jaya jaya"),
     *                      @OA\Property(property="kompetensi", type="string", example=""),
     *                      @OA\Property(property="cp", type="string", example="08"),
     *                      @OA\Property(property="is_aktif", type="string", example="1"),
     *                      @OA\Property(property="is_eksternal", type="string", example="1"),
     *                      @OA\Property(property="info_left", type="integer", example=1),
     *                      @OA\Property(property="info_right", type="integer", example=8),
     *                      @OA\Property(property="id_ketua", type="integer", example=1),
     *                      @OA\Property(property="id_sekretaris", type="integer", example=1),
     *                      @OA\Property(property="id_pembantu_1", type="integer", example=1),
     *                      @OA\Property(property="id_pembantu_2", type="integer", example=1),
     *                      @OA\Property(property="id_pembantu_3", type="integer", example=1),
     *                      @OA\Property(property="id_pembantu_4", type="integer", example=1),
     *                  ),
     *              ),
     *              @OA\Property(property="info", type="object",
     *                      @OA\Property(property="total", type="integer", example=10),
     *                      @OA\Property(property="page", type="integer", example=1),
     *                      @OA\Property(property="last_page", type="integer", example=1),
     *                      @OA\Property(property="count", type="integer", example=10),
     *                      @OA\Property(property="start", type="integer", example=1),
     *                      @OA\Property(property="end", type="integer", example=10),
     *              ),
     *              @OA\Property(property="debug", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="query", type="string", example="select count(*) as aggregate from ms_unit"),
     *                      @OA\Property(property="time", type="integer", example=59.0),
     *                  ),
     *              ),
     *          ),
     *       ),
     * )
     */

    /**
     * @OA\Get(
     *     path="/v1/unit/{id}",
     *     summary="Data Unit",
     *     tags={"Unit"},
     *     security={{"bearerAuth": {}}},
     *     @OA\Parameter(
     *         description="id unit",
     *         in="path",
     *         name="id",
     *         required=true,
     *         @OA\Schema(type="integer"),
     *         @OA\Examples(example="int", value="1", summary="An int value."),
     *     ),
     *     @OA\Response(
     *          response=200,
     *          description="Get data of unit.",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(property="data", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="id", type="integer", example=1),
     *                      @OA\Property(property="id_pt", type="integer", example=1),
     *                      @OA\Property(property="nama_unit", type="string", example="Teknik Elektro"),
     *                      @OA\Property(property="nama_unit_en", type="string", example="Electrical Engineering"),
     *                      @OA\Property(property="nama_singkat", type="string", example="Teknik Elektro"),
     *                      @OA\Property(property="id_parent", type="integer", example=1),
     *                      @OA\Property(property="id_jenjang", type="integer", example=1),
     *                      @OA\Property(property="jenis_unit", type="string", example="P"),
     *                      @OA\Property(property="alamat", type="string", example="Jl. Sima"),
     *                      @OA\Property(property="telepon", type="string", example="08"),
     *                      @OA\Property(property="email", type="string", example="elektro@unila.ac.id"),
     *                      @OA\Property(property="website", type="string", example="elektro.unila.ac.id"),
     *                      @OA\Property(property="gelar", type="string", example="S.T."),
     *                      @OA\Property(property="gelar_en", type="string", example="S.T."),
     *                      @OA\Property(property="deskripsi_gelar", type="string", example="Sarjana Teknik (elektro)"),
     *                      @OA\Property(property="deskripsi_gelar_en", type="string", example="Bachelor of Engineering (Electrical)"),
     *                      @OA\Property(property="akreditasi", type="string", example="A"),
     *                      @OA\Property(property="sk_akreditasi", type="string", example="UIDA-SK-A-01/UNILA/2019"),
     *                      @OA\Property(property="tgl_akreditasi", type="date", example="2021-01-01"),
     *                      @OA\Property(property="tgl_sk_pendirian", type="date", example="2019-01-01"),
     *                      @OA\Property(property="id_periode_berdiri", type="integer", example=1),
     *                      @OA\Property(property="sks_lulus_min", type="integer", example=144),
     *                      @OA\Property(property="ipk_lulus_min", type="decimal", example=2.75),
     *                      @OA\Property(property="batas_sks_awal", type="integer", example=18),
     *                      @OA\Property(property="jumlah_pembimbing", type="integer", example=30),
     *                      @OA\Property(property="jumlah_penguji", type="integer", example=25),
     *                      @OA\Property(property="id_jenis_ta", type="string", example=1),
     *                      @OA\Property(property="kode_nim", type="string", example="021"),
     *                      @OA\Property(property="foto", type="string", example="http"),
     *                      @OA\Property(property="keterangan", type="string", example="Teknik elektro"),
     *                      @OA\Property(property="visi", type="string", example="elektro jaya"),
     *                      @OA\Property(property="misi", type="string", example="jaya jaya jaya"),
     *                      @OA\Property(property="kompetensi", type="string", example=""),
     *                      @OA\Property(property="cp", type="string", example="08"),
     *                      @OA\Property(property="is_aktif", type="string", example="1"),
     *                      @OA\Property(property="is_eksternal", type="string", example="1"),
     *                      @OA\Property(property="info_left", type="integer", example=1),
     *                      @OA\Property(property="info_right", type="integer", example=8),
     *                      @OA\Property(property="id_ketua", type="integer", example=1),
     *                      @OA\Property(property="id_sekretaris", type="integer", example=1),
     *                      @OA\Property(property="id_pembantu_1", type="integer", example=1),
     *                      @OA\Property(property="id_pembantu_2", type="integer", example=1),
     *                      @OA\Property(property="id_pembantu_3", type="integer", example=1),
     *                      @OA\Property(property="id_pembantu_4", type="integer", example=1),
     *                  ),
     *              ),
     *              @OA\Property(property="debug", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="query", type="string", example="SELECT * FROM ms_unit WHERE ms_unit.id = 1 limit 1"),
     *                      @OA\Property(property="time", type="integer", example=59.0),
     *                  ),
     *              ),
     *          ),
     *     ),
     *     @OA\Response(response=404, description="Error: Not Found",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(property="error", type="object",
     *                      @OA\Property(property="code", type="integer", example=404),
     *                      @OA\Property(property="message", type="string", example="Data tidak ditemukan"),
     *                      @OA\Property(property="debug", type="object",
     *                          @OA\Property(property="message", type="string", example="No query results for model [App\Models\Unit] 1"),
     *                          @OA\Property(property="files", type="object",
     *                              @OA\Property(type="string", example="/Users/brondol/Applications/siakadcloud/master/vendor/illuminate/database/Eloquent/Builder.php baris 434"),
     *                          ),
     *                      ),
     *              ),
     *              @OA\Property(property="debug", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="query", type="string", example="select * from ak_mahasiswa where ak_mahasiswa.id = 1 limit 1"),
     *                      @OA\Property(property="time", type="integer", example=2.25),
     *                  ),
     *              ),
     *          ),
     *     ),
     * )
     */

    /**
     * @OA\Post(
     *     path="/v1/unit",
     *     summary="Add Unit",
     *     tags={"Unit"},
     *     security={{"bearerAuth": {}}},
     *     @OA\RequestBody(
     *         @OA\MediaType(
     *             mediaType="application/json",
     *             @OA\Schema(
     * required={"nama_unit", "jenis_unit","is_aktif", "is_eksternal", "info_left", "info_right"},
     *                 @OA\Property(property="nama_unit", type="string", example="Teknik Elektro"),
     *                 @OA\Property(property="nama_unit_en", type="string", example="Electrical Engineering"),
     *                 @OA\Property(property="nama_singkat", type="string", example="Teknik Elektro"),
     *                 @OA\Property(property="id_parent", type="integer", example=1),
     *                 @OA\Property(property="id_jenjang", type="integer", example=1),
     *                 @OA\Property(property="jenis_unit", type="string", example="P"),
     *                 @OA\Property(property="alamat", type="string", example="Jl. Sima"),
     *                 @OA\Property(property="telepon", type="string", example="08"),
     *                 @OA\Property(property="email", type="string", example="elektro@unila.ac.id"),
     *                 @OA\Property(property="website", type="string", example="elektro.unila.ac.id"),
     *                 @OA\Property(property="gelar", type="string", example="S.T."),
     *                 @OA\Property(property="gelar_en", type="string", example="S.T."),
     *                 @OA\Property(property="deskripsi_gelar", type="string", example="Sarjana Teknik (elektro)"),
     *                 @OA\Property(property="deskripsi_gelar_en", type="string", example="Bachelor of Engineering (Electrical)"),
     *                 @OA\Property(property="akreditasi", type="string", example="A"),
     *                 @OA\Property(property="sk_akreditasi", type="string", example="UIDA-SK-A-01/UNILA/2019"),
     *                 @OA\Property(property="tgl_akreditasi", type="date", example="2021-01-01"),
     *                 @OA\Property(property="tgl_sk_pendirian", type="date", example="2019-01-01"),
     *                 @OA\Property(property="id_periode_berdiri", type="integer", example=1),
     *                 @OA\Property(property="sks_lulus_min", type="integer", example=144),
     *                 @OA\Property(property="ipk_lulus_min", type="decimal", example=2.75),
     *                 @OA\Property(property="batas_sks_awal", type="integer", example=18),
     *                 @OA\Property(property="jumlah_pembimbing", type="integer", example=30),
     *                 @OA\Property(property="jumlah_penguji", type="integer", example=25),
     *                 @OA\Property(property="id_jenis_ta", type="string", example=1),
     *                 @OA\Property(property="kode_nim", type="string", example="021"),
     *                 @OA\Property(property="foto", type="string", example="http"),
     *                 @OA\Property(property="keterangan", type="string", example="Teknik elektro"),
     *                 @OA\Property(property="visi", type="string", example="elektro jaya"),
     *                 @OA\Property(property="misi", type="string", example="jaya jaya jaya"),
     *                 @OA\Property(property="kompetensi", type="string", example=""),
     *                 @OA\Property(property="cp", type="string", example="08"),
     *                 @OA\Property(property="is_aktif", type="string", example="1"),
     *                 @OA\Property(property="is_eksternal", type="string", example="1"),
     *                 @OA\Property(property="info_left", type="integer", example=1),
     *                 @OA\Property(property="info_right", type="integer", example=8),
     *                 @OA\Property(property="id_ketua", type="integer", example=1),
     *                 @OA\Property(property="id_sekretaris", type="integer", example=1),
     *                 @OA\Property(property="id_pembantu_1", type="integer", example=1),
     *                 @OA\Property(property="id_pembantu_2", type="integer", example=1),
     *                 @OA\Property(property="id_pembantu_3", type="integer", example=1),
     *                 @OA\Property(property="id_pembantu_4", type="integer", example=1),
     *             )
     *         )
     *     ),
     *     @OA\Response(
     *          response=201,
     *          description="Success add new unit.",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(property="data", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="id", type="integer", example=1),
     *                      @OA\Property(property="id_pt", type="integer", example=1),
     *                      @OA\Property(property="nama_unit", type="string", example="Teknik Elektro"),
     *                      @OA\Property(property="nama_unit_en", type="string", example="Electrical Engineering"),
     *                      @OA\Property(property="nama_singkat", type="string", example="Teknik Elektro"),
     *                      @OA\Property(property="id_parent", type="integer", example=1),
     *                      @OA\Property(property="id_jenjang", type="integer", example=1),
     *                      @OA\Property(property="jenis_unit", type="string", example="P"),
     *                      @OA\Property(property="alamat", type="string", example="Jl. Sima"),
     *                      @OA\Property(property="telepon", type="string", example="08"),
     *                      @OA\Property(property="email", type="string", example="elektro@unila.ac.id"),
     *                      @OA\Property(property="website", type="string", example="elektro.unila.ac.id"),
     *                      @OA\Property(property="gelar", type="string", example="S.T."),
     *                      @OA\Property(property="gelar_en", type="string", example="S.T."),
     *                      @OA\Property(property="deskripsi_gelar", type="string", example="Sarjana Teknik (elektro)"),
     *                      @OA\Property(property="deskripsi_gelar_en", type="string", example="Bachelor of Engineering (Electrical)"),
     *                      @OA\Property(property="akreditasi", type="string", example="A"),
     *                      @OA\Property(property="sk_akreditasi", type="string", example="UIDA-SK-A-01/UNILA/2019"),
     *                      @OA\Property(property="tgl_akreditasi", type="date", example="2021-01-01"),
     *                      @OA\Property(property="tgl_sk_pendirian", type="date", example="2019-01-01"),
     *                      @OA\Property(property="id_periode_berdiri", type="integer", example=1),
     *                      @OA\Property(property="sks_lulus_min", type="integer", example=144),
     *                      @OA\Property(property="ipk_lulus_min", type="decimal", example=2.75),
     *                      @OA\Property(property="batas_sks_awal", type="integer", example=18),
     *                      @OA\Property(property="jumlah_pembimbing", type="integer", example=30),
     *                      @OA\Property(property="jumlah_penguji", type="integer", example=25),
     *                      @OA\Property(property="id_jenis_ta", type="string", example=1),
     *                      @OA\Property(property="kode_nim", type="string", example="021"),
     *                      @OA\Property(property="foto", type="string", example="http"),
     *                      @OA\Property(property="keterangan", type="string", example="Teknik elektro"),
     *                      @OA\Property(property="visi", type="string", example="elektro jaya"),
     *                      @OA\Property(property="misi", type="string", example="jaya jaya jaya"),
     *                      @OA\Property(property="kompetensi", type="string", example=""),
     *                      @OA\Property(property="cp", type="string", example="08"),
     *                      @OA\Property(property="is_aktif", type="string", example="1"),
     *                      @OA\Property(property="is_eksternal", type="string", example="1"),
     *                      @OA\Property(property="info_left", type="integer", example=1),
     *                      @OA\Property(property="info_right", type="integer", example=8),
     *                      @OA\Property(property="id_ketua", type="integer", example=1),
     *                      @OA\Property(property="id_sekretaris", type="integer", example=1),
     *                      @OA\Property(property="id_pembantu_1", type="integer", example=1),
     *                      @OA\Property(property="id_pembantu_2", type="integer", example=1),
     *                      @OA\Property(property="id_pembantu_3", type="integer", example=1),
     *                      @OA\Property(property="id_pembantu_4", type="integer", example=1),
     *                  ),
     *              ),
     *              @OA\Property(property="debug", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="query", type="string", example="insert into ms_unit () values () returning id"),
     *                      @OA\Property(property="time", type="integer", example=8.13),
     *                  ),
     *              ),
     *          ),
     *     ),
     *     @OA\Response(response=400, description="Bad Request",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(property="error", type="object",
     *                      @OA\Property(property="code", type="integer", example=400),
     *                      @OA\Property(property="message", type="string", example="Data yang dikirimkan tidak valid"),
     *                      @OA\Property(property="validation", type="object",
     *                          @OA\Property(property="nama_field", type="array",
     *                              @OA\Items(type="string", example="Harus diisi"),
     *                          ),
     *                      ),
     *              ),
     *          ),
     *     ),
     * )
     */

    /**
     * @OA\Put(
     *     path="/v1/unit/{id}",
     *     summary="Update unit",
     *     tags={"Unit"},
     *     security={{"bearerAuth": {}}},
     *     @OA\Parameter(
     *         description="id unit",
     *         in="path",
     *         name="id",
     *         required=true,
     *         @OA\Schema(type="integer"),
     *         @OA\Examples(example="int", value="1", summary="An int value."),
     *     ),
     *     @OA\RequestBody(
     *         @OA\MediaType(
     *             mediaType="application/json",
     *             @OA\Schema(
     *                 @OA\Property(property="nama_unit", type="string", example="Teknik Elektro"),
     *                 @OA\Property(property="nama_unit_en", type="string", example="Electrical Engineering"),
     *                 @OA\Property(property="nama_singkat", type="string", example="Teknik Elektro"),
     *                 @OA\Property(property="id_parent", type="integer", example=1),
     *                 @OA\Property(property="id_jenjang", type="integer", example=1),
     *                 @OA\Property(property="jenis_unit", type="string", example="P"),
     *                 @OA\Property(property="alamat", type="string", example="Jl. Sima"),
     *                 @OA\Property(property="telepon", type="string", example="08"),
     *                 @OA\Property(property="email", type="string", example="elektro@unila.ac.id"),
     *                 @OA\Property(property="website", type="string", example="elektro.unila.ac.id"),
     *                 @OA\Property(property="gelar", type="string", example="S.T."),
     *                 @OA\Property(property="gelar_en", type="string", example="S.T."),
     *                 @OA\Property(property="deskripsi_gelar", type="string", example="Sarjana Teknik (elektro)"),
     *                 @OA\Property(property="deskripsi_gelar_en", type="string", example="Bachelor of Engineering (Electrical)"),
     *                 @OA\Property(property="akreditasi", type="string", example="A"),
     *                 @OA\Property(property="sk_akreditasi", type="string", example="UIDA-SK-A-01/UNILA/2019"),
     *                 @OA\Property(property="tgl_akreditasi", type="date", example="2021-01-01"),
     *                 @OA\Property(property="tgl_sk_pendirian", type="date", example="2019-01-01"),
     *                 @OA\Property(property="id_periode_berdiri", type="integer", example=1),
     *                 @OA\Property(property="sks_lulus_min", type="integer", example=144),
     *                 @OA\Property(property="ipk_lulus_min", type="decimal", example=2.75),
     *                 @OA\Property(property="batas_sks_awal", type="integer", example=18),
     *                 @OA\Property(property="jumlah_pembimbing", type="integer", example=30),
     *                 @OA\Property(property="jumlah_penguji", type="integer", example=25),
     *                 @OA\Property(property="id_jenis_ta", type="string", example=1),
     *                 @OA\Property(property="kode_nim", type="string", example="021"),
     *                 @OA\Property(property="foto", type="string", example="http"),
     *                 @OA\Property(property="keterangan", type="string", example="Teknik elektro"),
     *                 @OA\Property(property="visi", type="string", example="elektro jaya"),
     *                 @OA\Property(property="misi", type="string", example="jaya jaya jaya"),
     *                 @OA\Property(property="kompetensi", type="string", example=""),
     *                 @OA\Property(property="cp", type="string", example="08"),
     *                 @OA\Property(property="is_aktif", type="string", example="1"),
     *                 @OA\Property(property="is_eksternal", type="string", example="1"),
     *                 @OA\Property(property="info_left", type="integer", example=1),
     *                 @OA\Property(property="info_right", type="integer", example=8),
     *                 @OA\Property(property="id_ketua", type="integer", example=1),
     *                 @OA\Property(property="id_sekretaris", type="integer", example=1),
     *                 @OA\Property(property="id_pembantu_1", type="integer", example=1),
     *                 @OA\Property(property="id_pembantu_2", type="integer", example=1),
     *                 @OA\Property(property="id_pembantu_3", type="integer", example=1),
     *                 @OA\Property(property="id_pembantu_4", type="integer", example=1),
     *             )
     *         )
     *     ),
     *     @OA\Response(
     *          response=200,
     *          description="Success Update Unit.",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(property="data", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="id", type="integer", example=1),
     *                      @OA\Property(property="id_pt", type="integer", example=1),
     *                      @OA\Property(property="nama_unit", type="string", example="Teknik Elektro"),
     *                      @OA\Property(property="nama_unit_en", type="string", example="Electrical Engineering"),
     *                      @OA\Property(property="nama_singkat", type="string", example="Teknik Elektro"),
     *                      @OA\Property(property="id_parent", type="integer", example=1),
     *                      @OA\Property(property="id_jenjang", type="integer", example=1),
     *                      @OA\Property(property="jenis_unit", type="string", example="P"),
     *                      @OA\Property(property="alamat", type="string", example="Jl. Sima"),
     *                      @OA\Property(property="telepon", type="string", example="08"),
     *                      @OA\Property(property="email", type="string", example="elektro@unila.ac.id"),
     *                      @OA\Property(property="website", type="string", example="elektro.unila.ac.id"),
     *                      @OA\Property(property="gelar", type="string", example="S.T."),
     *                      @OA\Property(property="gelar_en", type="string", example="S.T."),
     *                      @OA\Property(property="deskripsi_gelar", type="string", example="Sarjana Teknik (elektro)"),
     *                      @OA\Property(property="deskripsi_gelar_en", type="string", example="Bachelor of Engineering (Electrical)"),
     *                      @OA\Property(property="akreditasi", type="string", example="A"),
     *                      @OA\Property(property="sk_akreditasi", type="string", example="UIDA-SK-A-01/UNILA/2019"),
     *                      @OA\Property(property="tgl_akreditasi", type="date", example="2021-01-01"),
     *                      @OA\Property(property="tgl_sk_pendirian", type="date", example="2019-01-01"),
     *                      @OA\Property(property="id_periode_berdiri", type="integer", example=1),
     *                      @OA\Property(property="sks_lulus_min", type="integer", example=144),
     *                      @OA\Property(property="ipk_lulus_min", type="decimal", example=2.75),
     *                      @OA\Property(property="batas_sks_awal", type="integer", example=18),
     *                      @OA\Property(property="jumlah_pembimbing", type="integer", example=30),
     *                      @OA\Property(property="jumlah_penguji", type="integer", example=25),
     *                      @OA\Property(property="id_jenis_ta", type="string", example=1),
     *                      @OA\Property(property="kode_nim", type="string", example="021"),
     *                      @OA\Property(property="foto", type="string", example="http"),
     *                      @OA\Property(property="keterangan", type="string", example="Teknik elektro"),
     *                      @OA\Property(property="visi", type="string", example="elektro jaya"),
     *                      @OA\Property(property="misi", type="string", example="jaya jaya jaya"),
     *                      @OA\Property(property="kompetensi", type="string", example=""),
     *                      @OA\Property(property="cp", type="string", example="08"),
     *                      @OA\Property(property="is_aktif", type="string", example="1"),
     *                      @OA\Property(property="is_eksternal", type="string", example="1"),
     *                      @OA\Property(property="info_left", type="integer", example=1),
     *                      @OA\Property(property="info_right", type="integer", example=8),
     *                      @OA\Property(property="id_ketua", type="integer", example=1),
     *                      @OA\Property(property="id_sekretaris", type="integer", example=1),
     *                      @OA\Property(property="id_pembantu_1", type="integer", example=1),
     *                      @OA\Property(property="id_pembantu_2", type="integer", example=1),
     *                      @OA\Property(property="id_pembantu_3", type="integer", example=1),
     *                      @OA\Property(property="id_pembantu_4", type="integer", example=1),
     *                  ),
     *              ),
     *              @OA\Property(property="debug", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="query", type="string", example="update ms_unit set ms_unit.id = 1 where ms_unit.id = 1"),
     *                      @OA\Property(property="time", type="integer", example=8.13),
     *                  ),
     *              ),
     *          ),
     *       ),
     *     @OA\Response(response=404, description="Error: Not Found",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(property="error", type="object",
     *                      @OA\Property(property="code", type="integer", example=404),
     *                      @OA\Property(property="message", type="string", example="Data tidak ditemukan"),
     *                      @OA\Property(property="debug", type="object",
     *                          @OA\Property(property="message", type="string", example="No query results for model [App\Models\Unit] 1"),
     *                          @OA\Property(property="files", type="object",
     *                              @OA\Property(type="string", example="/Users/brondol/Applications/siakadcloud/master/vendor/illuminate/database/Eloquent/Builder.php baris 434"),
     *                          ),
     *                      ),
     *              ),
     *              @OA\Property(property="debug", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="query", type="string", example="select * from ak_mahasiswa where ak_mahasiswa.id = 1 limit 1"),
     *                      @OA\Property(property="time", type="integer", example=2.25),
     *                  ),
     *              ),
     *          ),
     *     ),
     * )
     */

    /**
     * @OA\Delete(
     *     path="/v1/unit/{id}",
     *     summary="Delete unit",
     *     tags={"Unit"},
     *     security={{"bearerAuth": {}}},
     *     @OA\Parameter(
     *         description="id unit",
     *         in="path",
     *         name="id",
     *         required=true,
     *         @OA\Schema(type="integer"),
     *         @OA\Examples(example="int", value="1", summary="An int value."),
     *     ),
     *     @OA\Response(
     *          response=200,
     *          description="Berhasil Menghapus Unit"
     *       ),
     *     @OA\Response(response=404, description="Error: Not Found",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(property="error", type="object",
     *                      @OA\Property(property="code", type="integer", example=404),
     *                      @OA\Property(property="message", type="string", example="Data tidak ditemukan"),
     *                      @OA\Property(property="debug", type="object",
     *                          @OA\Property(property="message", type="string", example="No query results for model [App\Models\Unit] 1"),
     *                          @OA\Property(property="files", type="object",
     *                              @OA\Property(type="string", example="/Users/brondol/Applications/siakadcloud/master/vendor/illuminate/database/Eloquent/Builder.php baris 434"),
     *                          ),
     *                      ),
     *              ),
     *              @OA\Property(property="debug", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="query", type="string", example="select * from ak_mahasiswa where ak_mahasiswa.id = 1 limit 1"),
     *                      @OA\Property(property="time", type="integer", example=2.25),
     *                  ),
     *              ),
     *          ),
     *     ),
     * )
     */

    /**
     *     @OA\Schema(
     *         schema="Unit",
     *         @OA\Xml(name="Unit"),
     * required={"nama_unit", "jenis_unit","is_aktif", "is_eksternal", "info_left", "info_right"},
     *         @OA\Property(property="id", type="integer", example=1),
     *         @OA\Property(property="id_pt", type="integer", example=1),
     *         @OA\Property(property="nama_unit", type="string", example="Teknik Elektro"),
     *         @OA\Property(property="nama_unit_en", type="string", example="Electrical Engineering"),
     *         @OA\Property(property="nama_singkat", type="string", example="Teknik Elektro"),
     *         @OA\Property(property="id_parent", type="integer", example=1),
     *         @OA\Property(property="id_jenjang", type="integer", example=1),
     *         @OA\Property(property="jenis_unit", type="string", example="P"),
     *         @OA\Property(property="alamat", type="string", example="Jl. Simanungun No. 1"),
     *         @OA\Property(property="telepon", type="string", example="0812-3456-789"),
     *         @OA\Property(property="email", type="string", example="elektro@unila.ac.id"),
     *         @OA\Property(property="website", type="string", example="elektro.unila.ac.id"),
     *         @OA\Property(property="gelar", type="string", example="S.T."),
     *         @OA\Property(property="gelar_en", type="string", example="S.T."),
     *         @OA\Property(property="deskripsi_gelar", type="string", example="Sarjana Teknik (elektro)"),
     *         @OA\Property(property="deskripsi_gelar_en", type="string", example="Bachelor of Engineering (Electrical)"),
     *         @OA\Property(property="akreditasi", type="string", example="A"),
     *         @OA\Property(property="sk_akreditasi", type="string", example="UIDA-SK-A-01/UNILA/2019"),
     *         @OA\Property(property="tgl_akreditasi", type="date", example="2021-01-01"),
     *         @OA\Property(property="tgl_sk_pendirian", type="date", example="2019-01-01"),
     *         @OA\Property(property="id_periode_berdiri", type="integer", example=1),
     *         @OA\Property(property="sks_lulus_min", type="integer", example=144),
     *         @OA\Property(property="ipk_lulus_min", type="decimal", example=2.75),
     *         @OA\Property(property="batas_sks_awal", type="integer", example=18),
     *         @OA\Property(property="jumlah_pembimbing", type="integer", example=30),
     *         @OA\Property(property="jumlah_penguji", type="integer", example=25),
     *         @OA\Property(property="id_jenis_ta", type="string", example=1),
     *         @OA\Property(property="kode_nim", type="string", example="021"),
     *         @OA\Property(property="foto", type="string", example="https://siakadcloud.unila.ac.id/storage/foto/unit/1.jpg"),
     *         @OA\Property(property="keterangan", type="string", example="Teknik elektro"),
     *         @OA\Property(property="visi", type="string", example="elektro jaya"),
     *         @OA\Property(property="misi", type="string", example="jaya jaya jaya"),
     *         @OA\Property(property="kompetensi", type="string", example="best elektro"),
     *         @OA\Property(property="cp", type="string", example="0812-3456-789"),
     *         @OA\Property(property="is_aktif", type="string", example="1"),
     *         @OA\Property(property="is_eksternal", type="string", example="1"),
     *         @OA\Property(property="info_left", type="integer", example=1),
     *         @OA\Property(property="info_right", type="integer", example=8),
     *         @OA\Property(property="id_ketua", type="integer", example=1),
     *         @OA\Property(property="id_sekretaris", type="integer", example=1),
     *         @OA\Property(property="id_pembantu_1", type="integer", example=1),
     *         @OA\Property(property="id_pembantu_2", type="integer", example=1),
     *         @OA\Property(property="id_pembantu_3", type="integer", example=1),
     *         @OA\Property(property="id_pembantu_4", type="integer", example=1),
     *     ),
     */
}
