<?php

namespace App\Http\Controllers\V1;

use Siakad\Controller;

class UniversitasProdiController extends Controller
{
    /**
     *
     * @OA\Get(
     *      path="/v1/universitas-prodi",
     *      tags={"Universitas prodi"},
     *      summary="List Universitas prodi",
     *      security={{"bearerAuth": {}}},
     *      @OA\Response(
     *          response=200,
     *          description="Get list of universitas prodi.",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(property="data", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="id", type="integer", example=1),
     *                      @OA\Property(property="id_universitas", type="integer", example=1),
     *                      @OA\Property(property="kode_prodi", type="string", example="008-74-201"),
     *                      @OA\Property(property="nama_prodi", type="string", example="Hukum"),
     *                      @OA\Property(property="id_jenjang", type="integer", example=1),
     *                      @OA\Property(property="alamat", type="string", example="Jl. "),
     *                      @OA\Property(property="telepon", type="string", example="082222222222"),
     *                  ),
     *              ),
     *              @OA\Property(property="info", type="object",
     *                      @OA\Property(property="total", type="integer", example=10),
     *                      @OA\Property(property="page", type="integer", example=1),
     *                      @OA\Property(property="last_page", type="integer", example=1),
     *                      @OA\Property(property="count", type="integer", example=10),
     *                      @OA\Property(property="start", type="integer", example=1),
     *                      @OA\Property(property="end", type="integer", example=10),
     *              ),
     *              @OA\Property(property="debug", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="query", type="string", example="select count(*) as aggregate from ms_universitas_prodi"),
     *                      @OA\Property(property="time", type="integer", example=59.0),
     *                  ),
     *              ),
     *          ),
     *       ),
     * )
     */

    /**
     * @OA\Get(
     *     path="/v1/universitas-prodi/{id}",
     *     summary="Data Universitas prodi",
     *     tags={"Universitas prodi"},
     *     security={{"bearerAuth": {}}},
     *     @OA\Parameter(
     *         description="id universitas prodi",
     *         in="path",
     *         name="id",
     *         required=true,
     *         @OA\Schema(type="integer"),
     *         @OA\Examples(example="int", value="1", summary="An int value."),
     *     ),
     *     @OA\Response(
     *          response=200,
     *          description="Get data of universitas prodi.",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(property="data", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="id", type="integer", example=1),
     *                      @OA\Property(property="id_universitas", type="integer", example=1),
     *                      @OA\Property(property="kode_prodi", type="string", example="008-74-201"),
     *                      @OA\Property(property="nama_prodi", type="string", example="Hukum"),
     *                      @OA\Property(property="id_jenjang", type="integer", example=1),
     *                      @OA\Property(property="alamat", type="string", example="Jl. "),
     *                      @OA\Property(property="telepon", type="string", example="082222222222"),
     *                  ),
     *              ),
     *              @OA\Property(property="debug", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="query", type="string", example="SELECT * FROM ms_universitas_prodi WHERE ms_universitas_prodi.id = 1 limit 1"),
     *                      @OA\Property(property="time", type="integer", example=59.0),
     *                  ),
     *              ),
     *          ),
     *     ),
     *     @OA\Response(response=404, description="Error: Not Found",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(property="error", type="object",
     *                      @OA\Property(property="code", type="integer", example=404),
     *                      @OA\Property(property="message", type="string", example="Data tidak ditemukan"),
     *                      @OA\Property(property="debug", type="object",
     *                          @OA\Property(property="message", type="string", example="No query results for model [App\Models\UniversitasProdi] 1"),
     *                          @OA\Property(property="files", type="object",
     *                              @OA\Property(type="string", example="/Users/brondol/Applications/siakadcloud/master/vendor/illuminate/database/Eloquent/Builder.php baris 434"),
     *                          ),
     *                      ),
     *              ),
     *              @OA\Property(property="debug", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="query", type="string", example="select * from ak_mahasiswa where ak_mahasiswa.id = 1 limit 1"),
     *                      @OA\Property(property="time", type="integer", example=2.25),
     *                  ),
     *              ),
     *          ),
     *     ),
     * )
     */

    /**
     * @OA\Post(
     *     path="/v1/universitas-prodi",
     *     summary="Add Universitas prodi",
     *     tags={"Universitas prodi"},
     *     security={{"bearerAuth": {}}},
     *     @OA\RequestBody(
     *         @OA\MediaType(
     *             mediaType="application/json",
     *             @OA\Schema(
     * required={"id_universitas", "kode_prodi", "nama_prodi"},
     *                 @OA\Property(property="id_universitas", type="integer", example=1),
     *                 @OA\Property(property="kode_prodi", type="string", example="008-74-201"),
     *                 @OA\Property(property="nama_prodi", type="string", example="Hukum"),
     *                 @OA\Property(property="id_jenjang", type="integer", example=1),
     *                 @OA\Property(property="alamat", type="string", example="Jl. "),
     *                 @OA\Property(property="telepon", type="string", example="082222222222"),
     *             )
     *         )
     *     ),
     *     @OA\Response(
     *          response=201,
     *          description="Success add new universitas prodi.",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(property="data", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="id", type="integer", example=1),
     *                      @OA\Property(property="id_universitas", type="integer", example=1),
     *                      @OA\Property(property="kode_prodi", type="string", example="008-74-201"),
     *                      @OA\Property(property="nama_prodi", type="string", example="Hukum"),
     *                      @OA\Property(property="id_jenjang", type="integer", example=1),
     *                      @OA\Property(property="alamat", type="string", example="Jl. "),
     *                      @OA\Property(property="telepon", type="string", example="082222222222"),
     *                  ),
     *              ),
     *              @OA\Property(property="debug", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="query", type="string", example="insert into ms_universitas_prodi () values () returning id"),
     *                      @OA\Property(property="time", type="integer", example=8.13),
     *                  ),
     *              ),
     *          ),
     *     ),
     *     @OA\Response(response=400, description="Bad Request",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(property="error", type="object",
     *                      @OA\Property(property="code", type="integer", example=400),
     *                      @OA\Property(property="message", type="string", example="Data yang dikirimkan tidak valid"),
     *                      @OA\Property(property="validation", type="object",
     *                          @OA\Property(property="nama_field", type="array",
     *                              @OA\Items(type="string", example="Harus diisi"),
     *                          ),
     *                      ),
     *              ),
     *          ),
     *     ),
     * )
     */

    /**
     * @OA\Put(
     *     path="/v1/universitas-prodi/{id}",
     *     summary="Update universitas prodi",
     *     tags={"Universitas prodi"},
     *     security={{"bearerAuth": {}}},
     *     @OA\Parameter(
     *         description="id universitas prodi",
     *         in="path",
     *         name="id",
     *         required=true,
     *         @OA\Schema(type="integer"),
     *         @OA\Examples(example="int", value="1", summary="An int value."),
     *     ),
     *     @OA\RequestBody(
     *         @OA\MediaType(
     *             mediaType="application/json",
     *             @OA\Schema(
     *                 @OA\Property(property="id_universitas", type="integer", example=1),
     *                 @OA\Property(property="kode_prodi", type="string", example="008-74-201"),
     *                 @OA\Property(property="nama_prodi", type="string", example="Hukum"),
     *                 @OA\Property(property="id_jenjang", type="integer", example=1),
     *                 @OA\Property(property="alamat", type="string", example="Jl. "),
     *                 @OA\Property(property="telepon", type="string", example="082222222222"),
     *             )
     *         )
     *     ),
     *     @OA\Response(
     *          response=200,
     *          description="Success Update Universitas prodi.",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(property="data", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="id", type="integer", example=1),
     *                      @OA\Property(property="id_universitas", type="integer", example=1),
     *                      @OA\Property(property="kode_prodi", type="string", example="008-74-201"),
     *                      @OA\Property(property="nama_prodi", type="string", example="Hukum"),
     *                      @OA\Property(property="id_jenjang", type="integer", example=1),
     *                      @OA\Property(property="alamat", type="string", example="Jl. "),
     *                      @OA\Property(property="telepon", type="string", example="082222222222"),
     *                  ),
     *              ),
     *              @OA\Property(property="debug", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="query", type="string", example="update ms_universitas_prodi set ms_universitas_prodi.id = 1 where ms_universitas_prodi.id = 1"),
     *                      @OA\Property(property="time", type="integer", example=8.13),
     *                  ),
     *              ),
     *          ),
     *       ),
     *     @OA\Response(response=404, description="Error: Not Found",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(property="error", type="object",
     *                      @OA\Property(property="code", type="integer", example=404),
     *                      @OA\Property(property="message", type="string", example="Data tidak ditemukan"),
     *                      @OA\Property(property="debug", type="object",
     *                          @OA\Property(property="message", type="string", example="No query results for model [App\Models\UniversitasProdi] 1"),
     *                          @OA\Property(property="files", type="object",
     *                              @OA\Property(type="string", example="/Users/brondol/Applications/siakadcloud/master/vendor/illuminate/database/Eloquent/Builder.php baris 434"),
     *                          ),
     *                      ),
     *              ),
     *              @OA\Property(property="debug", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="query", type="string", example="select * from ak_mahasiswa where ak_mahasiswa.id = 1 limit 1"),
     *                      @OA\Property(property="time", type="integer", example=2.25),
     *                  ),
     *              ),
     *          ),
     *     ),
     * )
     */

    /**
     * @OA\Delete(
     *     path="/v1/universitas-prodi/{id}",
     *     summary="Delete universitas prodi",
     *     tags={"Universitas prodi"},
     *     security={{"bearerAuth": {}}},
     *     @OA\Parameter(
     *         description="id universitas prodi",
     *         in="path",
     *         name="id",
     *         required=true,
     *         @OA\Schema(type="integer"),
     *         @OA\Examples(example="int", value="1", summary="An int value."),
     *     ),
     *     @OA\Response(
     *          response=200,
     *          description="Berhasil Menghapus Universitas prodi"
     *       ),
     *     @OA\Response(response=404, description="Error: Not Found",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(property="error", type="object",
     *                      @OA\Property(property="code", type="integer", example=404),
     *                      @OA\Property(property="message", type="string", example="Data tidak ditemukan"),
     *                      @OA\Property(property="debug", type="object",
     *                          @OA\Property(property="message", type="string", example="No query results for model [App\Models\UniversitasProdi] 1"),
     *                          @OA\Property(property="files", type="object",
     *                              @OA\Property(type="string", example="/Users/brondol/Applications/siakadcloud/master/vendor/illuminate/database/Eloquent/Builder.php baris 434"),
     *                          ),
     *                      ),
     *              ),
     *              @OA\Property(property="debug", type="array",
     *                  @OA\Items(type="object",
     *                      @OA\Property(property="query", type="string", example="select * from ak_mahasiswa where ak_mahasiswa.id = 1 limit 1"),
     *                      @OA\Property(property="time", type="integer", example=2.25),
     *                  ),
     *              ),
     *          ),
     *     ),
     * )
     */

    /**
     *     @OA\Schema(
     *         schema="Universitas prodi",
     *         @OA\Xml(name="Universitas prodi"),
     * required={"id_universitas", "kode_prodi", "nama_prodi"},
     *         @OA\Property(property="id", type="integer", example=1),
     *         @OA\Property(property="id_universitas", type="integer", example=1),
     *         @OA\Property(property="kode_prodi", type="string", example="008-74-201"),
     *         @OA\Property(property="nama_prodi", type="string", example="Hukum"),
     *         @OA\Property(property="id_jenjang", type="integer", example=1),
     *         @OA\Property(property="alamat", type="string", example="Jl. Makmur"),
     *         @OA\Property(property="telepon", type="string", example="082222222222"),
     *     ),
     */
}
